### PR TITLE
feat: add new image styles, create view modes, and expose them via wysiwyg

### PR DESCRIPTION
**Pull request by bryanbraun**
# READY FOR REVIEW

Note: Please do not merge until @pookmish gets a chance to look at this.

## Summary

The goal was to add new image styles to the WYSIWYG editor as requested by the H&S team:

existing-wysiwyg-image-displays (1)

**New Image Styles**

- Large Square (480x480)
- Small Scaled (182px)
- Medium Scaled (352px)
- Large Scaled (480px)
- XL Scaled (610px)

**New View Modes**

- Small Square (stanford_image_small)
- XL Square (stanford_image_xl)
- Small Scaled (stanford_image_small_scaled)
- Medium Scaled (stanford_image_medium_scaled)
- Large Scaled (stanford_image_large_scaled)
- XL Scaled (stanford_image_xl_scaled)

**Updated View Modes**

- Large Square renamed to XL Square

## Need Review By (Date)
asap

## Urgency
medium

## Steps to Test
1. Pull down this branch
2. Import all the configuration for these image styles and view modes.
    - `lando drush @mysite.local config-import`
    - Warning: this will impact your local environment significantly:
3. Go to a basic page, create a Text Area Paragraph, insert each of the image styles and confirm that they work as expected (including with floats, etc)
4. Check for regressions.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

### CODE REVIEW

**Comment by heatherdesigns** [comment]
@bryanbraun I was unable to import the configuration changes. Here's output from my CLI:
import failed

**Comment by pookmish** [comment]
@heatherdesigns be sure to run `composer install` any time you checkout a new branch or after running `git pull` this will ensure you have the latest dependencies such as devel_php

**Comment by heatherdesigns** [comment]
@bryanbraun In `config/default/responsive_image.styles.square.yml`, update references to `hs_large_square_700x700` to `hs_xlarge_square_700x700`.

**Comment by bryanbraun** [comment]
Good catch @heatherdesigns, I'll push up that fix shortly.

We got a small update from Alex to change a couple of the image widths so I hope to have that adjustment ready by tomorrow morning.

@heatherdesigns, did you see this error when you did a local `config-import`?

```
 [error]  Drupal\Core\Config\ConfigException: Errors occurred during import in Drush\Drupal\Commands\config\ConfigImportCommands->doImport() (line 249 of /var/www/html/vendor/drush/drush/src/Drupal/Commands/config/ConfigImportCommands.php). 

In ConfigImportCommands.php line 263:
                                                                               
  [Exception]                                                                  
  The import failed due to the following reasons:                              
  Unexpected error during import with operation create for image.style.hs_xla  
  rge_square_700x700: Attempt to save a configuration entity &#039;hs_xlarge_  
  square_700x700&#039; with UUID &#039;48ebce82-ab26-47a8-b296-95c9aa3d2723&#  
  039; when this UUID is already used for &#039;hs_large_square_700x700&#039;  
                                                                               
```

This is the error we're currently seeing in Circle CI. Unexpected, since all of my changes were made in the UI and then exported (none of them were made directly to the yaml files). Many machine names aren't editable in the UI but this images styles one was. 🤔

Ever seen this before @pookmish?

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr507-7bfxlir07ydfaf8i7kcibzpe78phus5u.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e5deb9fed1965879d4722ae

**Comment by bryanbraun** [comment]
That config error is weird... it isn't happening for imports locally.

I think I might just delete and recreate this specific image style so it generates a new UUID. Hopefully that will take care of it.

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr507-7bfxlir07ydfaf8i7kcibzpe78phus5u.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e5deb9fed1965879d4722ae

**Pull request closed without merging**
