### PR TITLE
SHS-8: Codeception testing private page

### PR DESCRIPTION
**Pull request by codechefmarc**
# READY FOR REVIEW

## Summary
Splits the private page test out to two different tests - permissions and content. The permissions test will test all roles viewing a private page. The content test will test to see if certain elements are available on the node edit form.

## Need Review By (Date)
09/07

## Urgency
low

## Steps to Test
1. run Codeception tests for permissions: ```blt codeception --group=permissions``` and verify that all tests pass.
2. run Codeception tests for content: ```blt codeception --group=content``` and verify that all tests pass.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1174-lagxu969g8pefncy0lwtpgc1ods33keh.tugboatqa.com
- https://hs-colorful-lagxu969g8pefncy0lwtpgc1ods33keh.tugboatqa.com
- https://hs-traditional-lagxu969g8pefncy0lwtpgc1ods33keh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6310e926aef88bc4d6d40f8f

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1174-lagxu969g8pefncy0lwtpgc1ods33keh.tugboatqa.com
- https://hs-colorful-lagxu969g8pefncy0lwtpgc1ods33keh.tugboatqa.com
- https://hs-traditional-lagxu969g8pefncy0lwtpgc1ods33keh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6310e926aef88bc4d6d40f8f

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1174-lagxu969g8pefncy0lwtpgc1ods33keh.tugboatqa.com
- https://hs-colorful-lagxu969g8pefncy0lwtpgc1ods33keh.tugboatqa.com
- https://hs-traditional-lagxu969g8pefncy0lwtpgc1ods33keh.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6310e926aef88bc4d6d40f8f

**Comment by callinmullaney** [comment]
@marcb4k These tests weren't running on CI due to the `@group` flag. I pushed a small change to add them to the `install` group (which probably should be the group given they are in the install directory) and they seem to be running/passing now. Approving to merge into our sprint 9 release branch.

**Pull request merged**
