### PR TITLE
HSD8-576 view field title

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Override the viewfield field type, widget and formatter to add the ability for the user to display and customize the title of the view if they so choose to.

# Needed By (Date)
- 2/13

# Urgency
- Medium

# Steps to Test
1. Checkout this branch
1. `composer install --prefer-source`
1. `blt drupal:sync --site=[sitename]`
1. add a new basic page and add a view field component
1. ensure the checkbox "Display view title", check that
1. ensure another checkbox appears to "Override Title", check that
1. ensure a text field appears for the "Overridden Title", populate that as desired
1. save and ensure your custom title displays above the view. if the view has no result, ensure no title is displayed.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
> 2/13

😆

**Comment by sherakama** [comment]
```
Notice: Undefined property: stdClass::$field_hs_view_show_title in Drupal\Core\Entity\Sql\SqlContentEntityStorage->loadFromDedicatedTables() (line 1179 of core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php).
```

After checking out this branch, syncing with philit, and then loading the home page.

**Comment by pookmish** [comment]
I don't get the same result. and CirleCi doesnt show any issues. what command are you running? @sherakama

**Comment by sherakama** [comment]
This might be me. I've discovered a few more issues and may have not sync'd successfully.

**Comment by sherakama** [comment]
I'll try to circle back to this today

**Review by boznik — APPROVED** [review]
This is working as expected

**Comment by sherakama** [comment]
Thanks @boznik

**Pull request merged**
