### PR TITLE
shs-56: fixes animation hero overlay

### PR DESCRIPTION
**Pull request by ryanhagerty**
## Summary
* fixes animation hero overlay
* also fixes discovered bug of text not displaying with no-js

## Steps to Test
1. Go to the tug boat links for colorful and traditional below
2. On the Colorful site, go to this page: `/components/hero-images-main-region`
3. Verify that the text displays for the `Hero (Gradient)` (first) and the `Hero (Overlay)` (third) component
4. Go to the theme settings page `admin/appearance/settings/humsci_colorful`, check 'Use Animation Enhancements' and verify step 3 again
5. Turn off JavaScript and verify step 3 again
6. Change the theme to the Traditional theme and verify steps 3 and 4 again

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1154-xczvwm3wm52kjbywthgfmrh1vkvc1uzf.tugboatqa.com
- https://hs-colorful-xczvwm3wm52kjbywthgfmrh1vkvc1uzf.tugboatqa.com
- https://hs-traditional-xczvwm3wm52kjbywthgfmrh1vkvc1uzf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62eabe55fe62828313696377

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1154-xczvwm3wm52kjbywthgfmrh1vkvc1uzf.tugboatqa.com
- https://hs-colorful-xczvwm3wm52kjbywthgfmrh1vkvc1uzf.tugboatqa.com
- https://hs-traditional-xczvwm3wm52kjbywthgfmrh1vkvc1uzf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62eabe55fe62828313696377

**Review by callinmullaney — APPROVED** [review]
@ryanhagerty Changes here look good to me :+1:

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1154-xczvwm3wm52kjbywthgfmrh1vkvc1uzf.tugboatqa.com
- https://hs-colorful-xczvwm3wm52kjbywthgfmrh1vkvc1uzf.tugboatqa.com
- https://hs-traditional-xczvwm3wm52kjbywthgfmrh1vkvc1uzf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62eabe55fe62828313696377

**Pull request merged**
