### PR TITLE
Sparkbox Sprint 7

### PR DESCRIPTION
**Pull request by kaseybon**
# READY FOR REVIEW

## Summary
- Reset Button styles [STN-153](https://sparkbox.atlassian.net/browse/STN-153) | PR #471
- Implement QA feedback Sprint 6 [STN-150](https://sparkbox.atlassian.net/browse/STN-150) | PR #472
- Decanter font-size update [STN-192](https://sparkbox.atlassian.net/browse/STN-192) | PR #491 
- Masthead [STN-117](https://sparkbox.atlassian.net/browse/STN-117) | PR #492 
- Global Footer [STN-69](https://sparkbox.atlassian.net/browse/STN-69 ) | PR #484
- Brand Lockup [STN-70](https://sparkbox.atlassian.net/browse/STN-70) | PR #485 
- Brand Bar [STN-68](https://sparkbox.atlassian.net/browse/STN-68) | PR #486 

## Need Review By (Date)
asap (2/18)

## Urgency
high

## Steps to Test
- ✅  We've verified that this branch passes the code climate and circle CI tests against the develop branch.

1. See other PRs if you'd like to test locally for those steps.
2. Verify code looking at the file changes here.
3. Go into `humsci_basic` folder directory and run `npm i` and `npm run test` to verify tests pass.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

### CODE REVIEW

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr488-lodloldt262bqmjslr4c8z0cicx23eqx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e46d2ce41ebe4cc94a15f26

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr488-lodloldt262bqmjslr4c8z0cicx23eqx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e46d2ce41ebe4cc94a15f26

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr488-lodloldt262bqmjslr4c8z0cicx23eqx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e46d2ce41ebe4cc94a15f26

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr488-lodloldt262bqmjslr4c8z0cicx23eqx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e46d2ce41ebe4cc94a15f26

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr488-lodloldt262bqmjslr4c8z0cicx23eqx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e46d2ce41ebe4cc94a15f26

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr488-lodloldt262bqmjslr4c8z0cicx23eqx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e46d2ce41ebe4cc94a15f26

**Comment by silverli** [comment]
@kaseybon I think we still need to add built styles too

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr488-lodloldt262bqmjslr4c8z0cicx23eqx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e46d2ce41ebe4cc94a15f26

**Review by pookmish — APPROVED** [review]

**Pull request merged**
