### PR TITLE
HSD8-000: Move Acquia clean up tasks from CircleCI to Github Actions

### PR DESCRIPTION
**Pull request by joegl**
# READY FOR REVIEW

## Summary
* Moved Acquia clean up tasks from CircleCI to Github Actions
* Changed `getAll()` method to `getNames()` method to reflect [changes in the SDK](https://github.com/typhonius/acquia-php-sdk-v2/commit/642b23ec5815e0b088d25ad077ed404ac2fbd276).

## Need Review By (Date)
Not urgent.

## Urgency
Not urgent.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1627-9hdjrw1rrtqhpuvoxvhirs5rz2sdozkk.tugboatqa.com
- https://hs-colorful-9hdjrw1rrtqhpuvoxvhirs5rz2sdozkk.tugboatqa.com
- https://hs-traditional-9hdjrw1rrtqhpuvoxvhirs5rz2sdozkk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66eb07aed48add63a7073527

Visual Diffs:
- https://dashboard.tugboatqa.com/66eb07aed48add63a7073527/visualdiffs

**Review by pookmish — APPROVED** [review]
LGTM. Just be aware, the cron jobs only run on the "default" branch, so this won't begin until it's merged into `develop`

**Comment by joegl** [comment]
> Member

Yea there's no urgency to get these in now but I was wondering if I should just merge it straight into the develop branch and then merge develop back into 11.2.5-release

**Comment by pookmish** [comment]
Meh, you're running it manually so it'll be fine to wait until the next release.

**Pull request merged**
