### PR TITLE
HSD8-666 Provision gavin-wright.humsci.stanford.edu

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Provision new site: gavin-wright.humsci.stanford.edu

# Needed By (Date)
- asap

# Urgency
- high (gotta get it in this release)

# Steps to Test
1. review code
1. optionally checkout this branch
1. ensure `drush @gavin_wright__humsci.local st` responds with applicable information.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
What's up with the Williams site? Is that extra?

**Review by sherakama — CHANGES_REQUESTED** [review]
Please confirm you wish to have the Williams site files in this PR.

**Comment by pookmish** [comment]
oh why did that come back :rage:

**Comment by pookmish** [comment]
Ok williams files deleted. i'll have to see why those got re-created

**Pull request merged**
