### PR TITLE
SHS-5782: Vertical button card fix text gets truncated / SHS-5793: Implementation: Vertical Button Card button is currently styled as a rectangle

### PR DESCRIPTION
**Pull request by mariannuar**
# READY FOR REVIEW

## Summary
Fix the button text getting truncated in Vertical Button Card in Colorful
Fix currently button style in Vertical Button Card in Colorful
Fix issue when Vertical Button Card with no title or no description

## Need Review By (Date)
09/04

## Urgency
medium

## Steps to Test
1. Go to [Colorful](https://hs-colorful-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com/components/collections/collections-postcards/vertical-button-cards-0/vertical-button-cards-0)
2. Check button style looks according to what's in the [design](https://www.figma.com/design/hOtD5MStjFIavUrWapHKHN/UX%2FDesign-Tickets-Work?node-id=4497-3745&t=gfAySXTRsOeLNSB3-4)
3. Check button text now forces hyphenation and respect the margins
4. Check that Vertical Button Card looks good in [these different scenarios](https://www.figma.com/design/hOtD5MStjFIavUrWapHKHN/UX%2FDesign-Tickets-Work?node-id=4738-155&t=gfAySXTRsOeLNSB3-4)
5. Now go to [Traditional](https://hs-traditional-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com/components/collections-0/collections-postcards/vertical-button-cards/vertical-button-cards-well)
6. And check that Vertical Button Card looks good in [these different scenarios](https://www.figma.com/design/hOtD5MStjFIavUrWapHKHN/UX%2FDesign-Tickets-Work?node-id=4790-440&t=gfAySXTRsOeLNSB3-4)

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208192527102423

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1613-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com
- https://hs-colorful-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com
- https://hs-traditional-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66cfe5dc1976d43229ca605a

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1613-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com
- https://hs-colorful-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com
- https://hs-traditional-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66cfe5dc1976d43229ca605a

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1613-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com
- https://hs-colorful-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com
- https://hs-traditional-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66cfe5dc1976d43229ca605a

Visual Diffs:
- https://dashboard.tugboatqa.com/66cfe5dc1976d43229ca605a/visualdiffs

**Review by cienvaras — CHANGES_REQUESTED** [review]
@mariannuar Looks good, just found a couple of issues that need a fix:

- Spacing below the title is very large in colorful when there's no description or button. This was not the case before, I think you removed a rule or change the specificity and a rule from other card variant is taking over:
    Screenshot 2024-09-03 at 10 34 14 AM
- There's an empty wrapper when the description is empty, which adds extra spacing. I saw it in traditional, but it might be happening in colorful too. Ideally, the markup shouldn't be present if empty, but if not possible try at least to remove the spacing:
    Screenshot 2024-09-03 at 10 48 44 AM

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1613-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com
- https://hs-colorful-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com
- https://hs-traditional-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66cfe5dc1976d43229ca605a

Visual Diffs:
- https://dashboard.tugboatqa.com/66cfe5dc1976d43229ca605a/visualdiffs

**Comment by mariannuar** [comment]
@cienvaras Thank you for your feedback! This is ready for review again!

**Review by cienvaras — APPROVED** [review]
@mariannuar LGTM, thanks for the fixes!

@ahughes3 Ready for your review. Plase note that this PR includes both [SHS-5793](https://app.clickup.com/t/36718269/SHS-5793) and [SHS-5782](https://app.clickup.com/t/36718269/SHS-5782)

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1613-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com
- https://hs-colorful-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com
- https://hs-traditional-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66cfe5dc1976d43229ca605a

Visual Diffs:
- https://dashboard.tugboatqa.com/66cfe5dc1976d43229ca605a/visualdiffs

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1613-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com
- https://hs-colorful-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com
- https://hs-traditional-5twp4oteg8kiutpmqkq0r9agn2688xbx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66cfe5dc1976d43229ca605a

Visual Diffs:
- https://dashboard.tugboatqa.com/66cfe5dc1976d43229ca605a/visualdiffs

**Comment by cienvaras** [comment]
@ahughes3 The border radius of the buttons is fixed, based on Katy's input. It's ready for testing again.

**Review by ahughes3 — APPROVED** [review]
Looks good,Thanks!

**Review by joegl — APPROVED** [review]

**Pull request merged**
