### PR TITLE
SHS-5899: BUG | Fix placement of button in exposed filters

### PR DESCRIPTION
**Pull request by mariannuar**
# READY FOR REVIEW

## Summary
Fix placement of button in exposed filters

## Need Review By (Date)
11/06

## Urgency
medium

## Steps to Test
1. Go to https://english.suhumsci.loc/people/lecturers or any site with exposed filters
2. Verify that the placement of the Apply button and Reset link are not affected by the dropdown option selected. They should stay vertically aligned with the top.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208693055424776

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1675-h9ny7lex9wnmmug1tub1e62vxxv4jsom.tugboatqa.com
- https://hs-colorful-h9ny7lex9wnmmug1tub1e62vxxv4jsom.tugboatqa.com
- https://hs-traditional-h9ny7lex9wnmmug1tub1e62vxxv4jsom.tugboatqa.com
- https://english-h9ny7lex9wnmmug1tub1e62vxxv4jsom.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6723acab6ec433609aea95de

Visual Diffs:
- https://dashboard.tugboatqa.com/6723acab6ec433609aea95de/visualdiffs

**Review by ahughes3 — APPROVED** [review]
We were able to recreate the filters here to test - https://hs-colorful-h9ny7lex9wnmmug1tub1e62vxxv4jsom.tugboatqa.com/default-views/publications

Looks good!

**Review by cienvaras — APPROVED** [review]
@mariannuar LGTM, thanks!

**Comment by cienvaras** [comment]
@ahughes3 Thanks! I'll pass it along to Joe then.

**Review by joegl — APPROVED** [review]

**Pull request merged**
