### PR TITLE
8.1.6 Release

### PR DESCRIPTION
**Pull request by pookmish**
# DO NOT MERGE

### CODE REVIEW

**Comment by sherakama** [comment]
@pookmish Anyone get a chance to review this?

**Comment by pookmish** [comment]
the merged item was reviewed. other wise it was just dependency updates

**Comment by sherakama** [comment]
Ok, for visibility sake please leave a comment to whom did the code review.

**Comment by pookmish** [comment]
https://github.com/SU-HSDO/suhumsci/pull/374

**Pull request merged**
