### PR TITLE
Toot toot.... Tugboat

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Set up tugboat

# Need Review By (Date)
- its a nice to have but not needed

# Urgency
- super low

# Steps to Test
1. click on the tugboat links.
1. use the user password as `tugboat:tugboat`

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr414-vmhzpvrkdrkirucfsn6cja8vauu3dabx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5d9622f7521790339991de2d

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr414-vmhzpvrkdrkirucfsn6cja8vauu3dabx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5d9622f7521790339991de2d

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr414-vmhzpvrkdrkirucfsn6cja8vauu3dabx.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5d9622f7521790339991de2d

**Review by sherakama — APPROVED** [review]

**Comment by sherakama** [comment]
Im not going to ask questions about the config_installer or the double cim cim.

**Pull request merged**
