### PR TITLE
SHS-5792: Person Full Name/Auto Entity Label bug

### PR DESCRIPTION
**Pull request by codechefmarc**
# READY FOR REVIEW

## Summary
* Fixes auto Full Name for the Person content type - when entering only a First and Last Name and saving, now the Full Name is created correctly and not a random string of characters.

## Need Review By (Date)
2024-08-28

## Urgency
medium

## Steps to Test
1. Login to the site
2. Create a Person node
3. Enter a First Name and Last Name, but leave the Full Name field empty
4. Save the node
5. On the front-end, verify that the title is the first name + last name and no random characters appear

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208165007263139

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1611-rjlcqrv8leixzrsndwqgt1cjnnvpzjk5.tugboatqa.com
- https://hs-colorful-rjlcqrv8leixzrsndwqgt1cjnnvpzjk5.tugboatqa.com
- https://hs-traditional-rjlcqrv8leixzrsndwqgt1cjnnvpzjk5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ce771e562a46f6ec2bbb72

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1611-rjlcqrv8leixzrsndwqgt1cjnnvpzjk5.tugboatqa.com
- https://hs-colorful-rjlcqrv8leixzrsndwqgt1cjnnvpzjk5.tugboatqa.com
- https://hs-traditional-rjlcqrv8leixzrsndwqgt1cjnnvpzjk5.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66ce771e562a46f6ec2bbb72

Visual Diffs:
- https://dashboard.tugboatqa.com/66ce771e562a46f6ec2bbb72/visualdiffs

**Review by cienvaras — APPROVED** [review]
@codechefmarc Thanks, works as expected!

@ahughes3 Ready for your review.

**Review by ahughes3 — APPROVED** [review]
Works as expected and looks good, approved by H&S

**Review by joegl — APPROVED** [review]

**Pull request merged**
