### PR TITLE
HSD8-1639: Uninstall and deprecate ECK

### PR DESCRIPTION
**Pull request by joegl**
# READY FOR REVIEW

## Summary
Remove all remaining ECK configuration and code.
Remove the ECK dependencies from views.
Uninstall the ECK module.

## Need Review By (Date)
_['10/30', 'asap', etc.]_

## Urgency
_['low', 'medium', 'high', etc.]_

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Review by pookmish — COMMENTED** [review]
Looking at the update it looks good. The majority of the files are in the configs inside the modules which doesn't impact existing sites.
I'll test it out locally later today when I have a few minutes.

**Comment by joegl** [comment]
> Looking at the update it looks good. The majority of the files are in the configs inside the modules which doesn't impact existing sites. I'll test it out locally later today when I have a few minutes.

Yea the most important part is dropping the eck dependency from the views before uninstalling the module, otherwise the views would get deleted. The `install` configs would only affect new sites.

**Comment by joegl** [comment]
@pookmish Were you able to pull this down? I'd like to get it merged today if possible. Sorry for the short turnaround.

**Comment by pookmish** [comment]
I'll try it now.

**Review by pookmish — APPROVED** [review]
LGTM :+1:

**Pull request merged**
