### PR TITLE
SHS-5914: Update new Collection background color name from "Light" to "Vibrant"

### PR DESCRIPTION
**Pull request by cienvaras**
# READY FOR REVIEW

## Summary
Rename "Light" option to "Vibrant" in the Collection component background color field

## Need Review By (Date)
11/06

## Urgency
medium

## Steps to Test
1. Log in to the [Tugboat test site](https://pr1669-3otyxy8mawyfhlwomfj4jrb0rziib8us.tugboatqa.com/user/login)
2. Create a Flexible Page. Add a Collection component
3. Confirm that the "Light" option for the "Background Color" field is not present anymore and instead there's a new "Vibrant" option
4. Configure the Collection to use the "Vibrant" background color, add one or more components inside it and save the page. Confirm that the collection looks as expected.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208642172130786

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1669-3otyxy8mawyfhlwomfj4jrb0rziib8us.tugboatqa.com
- https://hs-colorful-3otyxy8mawyfhlwomfj4jrb0rziib8us.tugboatqa.com
- https://hs-traditional-3otyxy8mawyfhlwomfj4jrb0rziib8us.tugboatqa.com
- https://english-3otyxy8mawyfhlwomfj4jrb0rziib8us.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/671ed7b03e2dd2b98cf5e669

Visual Diffs:
- https://dashboard.tugboatqa.com/671ed7b03e2dd2b98cf5e669/visualdiffs

**Comment by cienvaras** [comment]
@ahughes3 Ready for review

**Review by ahughes3 — APPROVED** [review]
LGTM!

**Comment by ahughes3** [comment]
@joegl The H&S Web Team has a newsletter going out the first week of Nov. that includes an update about this feature. The team would like to have this label update included in this week's release in order to be on prod when the newsletter is sent to site editors. Can we treat this like a hotfix and include in this week's prod release?

**Comment by joegl** [comment]
> @joegl The H&S Web Team has a newsletter going out the first week of Nov. that includes an update about this feature. The team would like to have this label update included in this week's release in order to be on prod when the newsletter is sent to site editors. Can we treat this like a hotfix and include in this week's prod release?

Yea that should be fine. I'll probably merge this tomorrow.

**Review by joegl — APPROVED** [review]

**Pull request merged**
