### PR TITLE
shs-29: add title field to timeline component and style

### PR DESCRIPTION
**Pull request by ryanhagerty**
## Summary
This adds a title field to the vertical timeline component and styles.

## Steps to Test
1. Import the config and clear the cache if need be
2. Go to the example page for vertical timelines here: `components/vertical-timeline-without-and-collection`
3. Edit that page and add titles to a few of the examples
4. The title should be an H2 in markup, but styles differently
5. Make sure it shows up in the traditional theme

## Screenshots
Screen Shot 2022-08-22 at 1 35 14 PM

Screen Shot 2022-08-22 at 1 35 21 PM

## Notes
Let's put this in the next release to allow for testing.

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1163-1kpq2sf0zwafiw6djemx8fjgqqx5rjlf.tugboatqa.com
- https://hs-colorful-1kpq2sf0zwafiw6djemx8fjgqqx5rjlf.tugboatqa.com
- https://hs-traditional-1kpq2sf0zwafiw6djemx8fjgqqx5rjlf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6303c41da476796b1c8adc2f

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1163-1kpq2sf0zwafiw6djemx8fjgqqx5rjlf.tugboatqa.com
- https://hs-colorful-1kpq2sf0zwafiw6djemx8fjgqqx5rjlf.tugboatqa.com
- https://hs-traditional-1kpq2sf0zwafiw6djemx8fjgqqx5rjlf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6303c41da476796b1c8adc2f

**Review by callinmullaney — APPROVED** [review]
@ryanhagerty From a code perspective this looks good. I verified on the hs-colorful site that the new field is present and displays like your screenshots. I think the styling for the new title field looks good as well but I know the acceptance criteria around this was intentionally vague so the client can make additional tweaks.

I'd like to kick this over to @Gregg-Hendrix to verify functional of this PR and test the new field/styles on an actual site that uses the colorful and traditional themes before merging into our release.

**Comment by callinmullaney** [comment]
@Gregg-Hendrix Can you perform a functional test of this PR and spin up some actual site's that use the Colorful and Traditional themes? Please include screenshots in your review. The following site's use the corresponding theme's that you can spin-up and test:
Colorful: https://economics.suhumsci.loc
Traditional: https://islamicstudies.suhumsci.loc

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1163-1kpq2sf0zwafiw6djemx8fjgqqx5rjlf.tugboatqa.com
- https://hs-colorful-1kpq2sf0zwafiw6djemx8fjgqqx5rjlf.tugboatqa.com
- https://hs-traditional-1kpq2sf0zwafiw6djemx8fjgqqx5rjlf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6303c41da476796b1c8adc2f

**Review by callinmullaney — APPROVED** [review]
@ryanhagerty I went ahead and checked this PR on the links mentioned above and think this is ready for client review. Because the client may have additional style feedback with the new title field, lets kick this over to them for review and have them use the tugboat links. If all looks good we'll merge into our release for additional testing they may want to do.

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1163-1kpq2sf0zwafiw6djemx8fjgqqx5rjlf.tugboatqa.com
- https://hs-colorful-1kpq2sf0zwafiw6djemx8fjgqqx5rjlf.tugboatqa.com
- https://hs-traditional-1kpq2sf0zwafiw6djemx8fjgqqx5rjlf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6303c41da476796b1c8adc2f

**Pull request merged**
