### PR TITLE
fix(shs-5118): add to calendar theming

### PR DESCRIPTION
**Pull request by mndonx**
# READY FOR REVIEW

## Summary
This PR adds theming adjustments to the Add to Calendar component, based on [Figma designs](https://www.figma.com/proto/hOtD5MStjFIavUrWapHKHN/UX%2FDesign-Tickets-Work?type=design&node-id=640-102&t=LhLJzFZTEJQDsIJn-0&scaling=min-zoom&page-id=635%3A20&hide-ui=1).

## Urgency
medium

## Steps to Test
1. Visit a page like https://dlcl.stanford.edu/events/french-speaking-worlds-rejane-senac (local copy: https://dlcl.suhumsci.loc/events/french-speaking-worlds-rejane-senac) 
2. Verify that the theming adjustments match those in the [Figma design.](https://www.figma.com/proto/hOtD5MStjFIavUrWapHKHN/UX%2FDesign-Tickets-Work?type=design&node-id=640-102&t=LhLJzFZTEJQDsIJn-0&scaling=min-zoom&page-id=635%3A20&hide-ui=1)  

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by mndonx** [comment]
@cienvaras I just fixed that stray border issue. Like Tori said today, I think this one can continue through review, and we'll have a new PR for an UI / A11y changes.

**Comment by mndonx** [comment]
@cienvaras Ah, I take that back. It needs one more adjustment for hs_traditional. Sorry about that! I'll have it back in review shortly.

**Comment by mndonx** [comment]
OK @cienvaras Ready for review, for real this time!

**Review by cienvaras — CHANGES_REQUESTED** [review]
@mndonx Looks and works great. I'm not merging it yet because there are a couple of pending things:

- Remove the close button, as Tori requested
- Add the missing aria attributes

I also found a minor style issue when the menu is open and the button focused:

Screenshot 2023-12-22 at 15 33 54

**Comment by mndonx** [comment]
@cienvaras I think those outstanding issues have now been addressed. Ready for re-review. Thank you!

**Review by cienvaras — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
