### PR TITLE
SHS-5657: "Add media" is inconsistent

### PR DESCRIPTION
**Pull request by cienvaras**
# NOT READY FOR REVIEW

## Summary
- Temporary PR to test update to `stanford_media` module

## Need Review By (Date)
_['10/30', 'asap', etc.]_

## Urgency
medium

## Steps to Test
1. Login into the [tugboat test site](https://pr1680-itvsgxymopupc1gksduk0fanoyx7upep.tugboatqa.com/user/login)
2. Visit the [Add Media page](https://pr1680-itvsgxymopupc1gksduk0fanoyx7upep.tugboatqa.com/media/add)
3. Confirm that the "Bulk Upload" link includes the list of media types that can be added in bulk

Screenshot 2024-11-06 at 5 36 48 PM

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1680-itvsgxymopupc1gksduk0fanoyx7upep.tugboatqa.com
- https://hs-colorful-itvsgxymopupc1gksduk0fanoyx7upep.tugboatqa.com
- https://hs-traditional-itvsgxymopupc1gksduk0fanoyx7upep.tugboatqa.com
- https://english-itvsgxymopupc1gksduk0fanoyx7upep.tugboatqa.com
- https://history-itvsgxymopupc1gksduk0fanoyx7upep.tugboatqa.com
- https://west-itvsgxymopupc1gksduk0fanoyx7upep.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/672bfc0a8e2485d441e7a069

**Comment by cienvaras** [comment]
@ahughes3 Created this temporary PR for testing the functionality in tugboat. ~~For some reason I'm not able to login into any of the test sites, I think that there's probably a tugboat configuration issue. I'll check tomorrow to see what's going on~~.

Some considerations:
- I created [a PR](https://github.com/SU-SWS/stanford_media/pull/158) against [https://github.com/SU-SWS/stanford_media](SWS `stanford_media`) repo with the change.
- The latest version of `stanford_media` is `11.1.2` which requires Drupal 10.3. That means that my change will probably have to wait until the H&S platform is updated to that Drupal version to see the changes in production.

**Comment by cienvaras** [comment]
@ahughes3 Just saw your message in Slack with the new tugboat credentials. Confirmed it works, just updated the testing instructions with direct links to the pages.

**Comment by pookmish** [comment]
No longer needed since https://github.com/SU-SWS/stanford_media/pull/158 has been merged and released in 11.1.3

**Pull request closed without merging**
