### PR TITLE
feat: use we_megamenu preprocess hook to add private page icon before private pages in dropdown

### PR DESCRIPTION
**Pull request by empee3**
# READY FOR REVIEW

## Summary
Currently, if there is a Drupal private page in the `we_megamenu` dropdown, there is no indicator present to make the user aware that the page is private. This PR uses the `we_megamenu` preprocess hook for list items to add a lock icon before the `<a>` element of a private page, matching how private pages are currently indicated in sidebar menus.

## Need Review By (Date)
asap

## Urgency
medium

## Steps to Test
1. Make sure the Mega Menu (`we_megamenu`) is installed, and its corresponding block is placed in the `Menu` region on your local environment. If not, follow the instructions in https://github.com/SU-HSDO/suhumsci/pull/1074 to set up the Mega Menu locally.
2. Be sure to be testing on a desktop view, since Mega Menu is a desktop-only feature.
3. Hover over the 'About' item in the Mega Menu navigation
4. Look for the link item title 'Private Page`
5. Verify that there is now a black lock icon preceding the 'Private Page` link text.

Screen Shot 2022-04-08 at 4 34 57 PM

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

### CODE REVIEW

**Comment by lunarfusion** [comment]
I think we should reduce the size of the icon a little where it appears within the dropdown submenu. We could add a class to vendor.we-megamenu-base.css. I did some in-browser overrides and this looks about right to me (the important tag is overriding another important tag):

.we-mega-menu-submenu .hb-private-page-link {
  padding-left: 3rem !important;
  background-size: 1.75rem 1.75rem;
}

So after line 185 of vendor.we-megamenu-base.css where we have the **&-submenu** class. What do you think?

**Comment by empee3** [comment]
You're right, this does look better! Update made!

> I think we should reduce the size of the icon a little where it appears within the dropdown submenu. We could add a class to vendor.we-megamenu-base.css. I did some in-browser overrides and this looks about right to me (the important tag is overriding another important tag):
> 
> .we-mega-menu-submenu .hb-private-page-link { padding-left: 3rem !important; background-size: 1.75rem 1.75rem; }
> 
> So after line 185 of vendor.we-megamenu-base.css where we have the **&-submenu** class. What do you think?

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr1089-carsdbaknqntbc4glopqlmql4fve6riq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/625584b07dc9604ba3f6dd16

**Comment by lunarfusion** [comment]
Looks good to me! Merging.

**Pull request merged**
