### PR TITLE
fk-sprint-3

### PR DESCRIPTION
**Pull request by ryanhagerty**
# READY FOR REVIEW

## Summary
This contains all the individual PRs for our current sprint.

These include (so far):
1. https://github.com/SU-HSDO/suhumsci/pull/1125

## Steps to Test
1. Please see individual PRs for testing instructions, or I'm happy to expand on anything individually.

### CODE REVIEW

**Comment by ryanhagerty** [comment]
👋  I made the base `develop` first so it could go through the checks and swapped over to the release branch.

**Comment by pookmish** [comment]
I just wanted to check if this was ready to merge into the release. I didn't see myself as assigned.

**Comment by ryanhagerty** [comment]
@pookmish Thanks for checking in. Yeah, this is ready. Do you prefer to be added as a reviewer and assignee or just assignee?

**Comment by pookmish** [comment]
Assignee is best when it's ready. Sometimes if you would like an early review, you can add me as a reviewer, though I'm not as responsive compared to the assignee designation.

**Review by pookmish — APPROVED** [review]

**Pull request merged**
