### PR TITLE
SHS-5810: Text "Main content start" appears after clicking "Skip to main content"

### PR DESCRIPTION
**Pull request by mariannuar**
# READY FOR REVIEW

## Summary
Fix main content start text after clicking skip to main content

## Need Review By (Date)
09/25

## Urgency
medium

## Steps to Test
1. Go to the homepage on Traditional or Colorful
2. Using a screen reader or only the keyboard
3. Press `Tab`
4. You will see the "Skip to main content".  Press `Enter`
5. Verify the text "Main content start" is not visible anymore

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208403963078981

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1632-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com
- https://hs-colorful-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com
- https://hs-traditional-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f1f25f6f1e8632c5a6c541

Visual Diffs:
- https://dashboard.tugboatqa.com/66f1f25f6f1e8632c5a6c541/visualdiffs

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1632-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com
- https://hs-colorful-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com
- https://hs-traditional-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f1f25f6f1e8632c5a6c541

Visual Diffs:
- https://dashboard.tugboatqa.com/66f1f25f6f1e8632c5a6c541/visualdiffs

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1632-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com
- https://hs-colorful-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com
- https://hs-traditional-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f1f25f6f1e8632c5a6c541

Visual Diffs:
- https://dashboard.tugboatqa.com/66f1f25f6f1e8632c5a6c541/visualdiffs

**Review by cienvaras — CHANGES_REQUESTED** [review]
@mariannuar We need to remove the extra spacing when the element is focused. I'm pretty sure you can remove the `focusable` class from the template as long as the element works as expected (can get focus, screen reader user get an indication of the focus change and can keep browsing from the new position).

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1632-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com
- https://hs-colorful-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com
- https://hs-traditional-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f1f25f6f1e8632c5a6c541

Visual Diffs:
- https://dashboard.tugboatqa.com/66f1f25f6f1e8632c5a6c541/visualdiffs

**Comment by mariannuar** [comment]
@cienvaras This is ready for review again. Thanks!

**Review by cienvaras — APPROVED** [review]
@mariannuar Works as expected, thanks!

@ahughes3 Ready for your review.

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1632-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com
- https://hs-colorful-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com
- https://hs-traditional-livvdmwpe04hrauspzjpptng5mhe6olq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f1f25f6f1e8632c5a6c541

Visual Diffs:
- https://dashboard.tugboatqa.com/66f1f25f6f1e8632c5a6c541/visualdiffs

**Review by ahughes3 — APPROVED** [review]

**Review by joegl — APPROVED** [review]

**Pull request merged**
