### PR TITLE
Arch 72 events template

### PR DESCRIPTION
**Pull request by pookmish**

### CODE REVIEW

**Comment by sherakama** [comment]
👀 No review?

**Comment by pookmish** [comment]
yeah thats my bad. Bad mike!

**Comment by pookmish** [comment]
reverting now

**Comment by sherakama** [comment]
Ok, the work that was committed is still reviewable. This is not production yet but review should still happen. Don't worry about reverting.

Greg and I can review the merged work and a new branch with fixes can be started.

**Comment by sherakama** [comment]
@boznik,

This work has been merged but please do take the time to review it and leave comments on this thread.

**Comment by pookmish** [comment]
thanks guys. crazy crazy week

**Pull request merged**
