### PR TITLE
Bugherd fixups

### PR DESCRIPTION
**Pull request by josephgknox**
# READY FOR REVIEW

# Summary
- Increased gutter between paragraph cards
- Expanded area for hovering when adding a new paragraph below an existing one (plus icon)

# Needed By (Date)
- End of sprint (9/26)

# Urgency
- N/A

# Steps to Test

1. Pull this branch
2. Ensure that the spacing between cards (homepage is a good place to test) has increased
3. Ensure that when editing a page you can now hover above the plus icon and to the right of the paragraph tab without losing the ability to add a new paragraph item below

# Affected Projects or Products
- Archaeology
- suhumsci (theme and admin theme)

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/ARCH-357
- https://stanfordits.atlassian.net/browse/ARCH-383

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
you've got some conflicts. why aren't we using a new branch for this work instead of using an old already merged branch

**Comment by josephgknox** [comment]
Merged in the latest from `develop`, which seems to have cleared up the conflicts.

Also, this is a new branch (but I have recycled the name of a previous branch since the work is related). Should I have appended the branch with a `-2` or something to differentiate it?

**Comment by pookmish** [comment]
2 choices
1. you can choose a different branch name
2. delete the branch on your local first, then recreate it. `git checkout develop; git branch -D branch-name; git checkout -b branch-name` then you can commit to it and it'll be good

**Comment by josephgknox** [comment]
Moved to https://github.com/SU-HSDO/suhumsci/pull/99

**Pull request closed without merging**
