### PR TITLE
SHS-64: Codeception test: Megamenu

### PR DESCRIPTION
**Pull request by codechefmarc**
# READY FOR REVIEW

## Summary
* Adds a Megamenu Codeception.
* Updates the Lando readme with instructions on how to set up Lando to test Codeception tests locally.

## Urgency
low

## Steps to Test
1. CI will run this test
2. If you wish to run this test locally, follow the steps in setting up a local environment with Lando and the new instructions for how to setup Lando for Codeception testing.
3. Run the test manually by running ```lando blt codeception --group=install``` However, this can overwhelm the local testing and cause errors so I recommend changing the group on line 9 in ```MegaMenuCest.php``` to ```megamenu``` and then running ```lando blt codeception --group=megamenu```.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Review by callinmullaney — CHANGES_REQUESTED** [review]
@marcb4k Test seems to run and pass. Also the documentation updated made sense to me and I was able to get codeception running through lando. I do have some feedback below for you to consider:
1. This test assumes a main menu already has links. This wouldn't be the case when initially installing a new platform site. I think we should consider creating a parent and child link first because this test will always fail for newer platform sites. Also, by seeding the menu with content first we can target menu links by their visual labels like `$I->canSee('Test Menu Item', '.megamenu__toggle');`
2. See `tests/codeception/functional/MediaCest.php` for reference. I think this test should be part of the `existingSite` group as well because platform sites (like Music Department) already have this feature active. 
3. Because we're spinning up an actual browser here I think we can now properly test mobile. Can you add another test that duplicates this one (`public function testMegaMenuMobile` maybe?) but specifically tests the mobile display? I think you'll need to include something like `$I->resizeWindow(800, 600);` at the beginning then include a step to toggle the whole menu open: 
```
$I->click('.js-megamenu__mobile-btn');
$I->seeElement('.js-megamenu__list--main.is-active');
```
4. Lastly, it's best practice for FE dev's to use a `.js-` prefixed class when it comes to writing markup that they know needs to be targeted via a JS function. This is done so long term maintenance is clear that "If I change this class I'm also breaking expected JS functionality somewhere". Not that you should know this but anytime you're writing a test that allows JS to run we should strive to target these classes if they are available. This will also allow tests to fail if JS is broken somewhere on the page; kind of a two-birds-with-one-stone coverage.

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by codechefmarc** [comment]
@callinmullaney - Thank you for the tips! I've added in the creation of menu items and also added a mobile test. Let me know if this update works.

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1196-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-colorful-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com
- https://hs-traditional-y71hw2xt9z784t9rxdl5oxouzztmldxy.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/633df796a4dc47a03a5d1864

**Pull request merged**
