### PR TITLE
SHS-5845: Collection with Well color for a page with a side bar menu

### PR DESCRIPTION
**Pull request by cienvaras**
# READY FOR REVIEW

## Summary
- Fix double spacing in full width wells in pages with sidebar

## Need Review By (Date)
10/09

## Urgency
medium

### Collections

1. In both [colorful](https://hs-colorful-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com/user/login) and [traditional](https://hs-traditional-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com/user/login) reference sites, log in and visit an existing flexible page with a visible sidebar. In that page, create 2 collections with a background color. In one of them select "Limited width" as the value for "Background Color Width", and in the other one select "Full width".
2. Visit the page and confirm that the horizontal spacing between the well border are the content is the same (32px in traditional and 48px in colorful) for both the "Limited Width" and the "Full Width" versions.
3. Alternatively, you visit a page with existing collections and change the value of "Background Color Width". Here are some pages that you can use:
    - Colorful
        - [Collection with Mixed Components in a Well](https://hs-colorful-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com/components/collections/collection-mixed-components/collection-mixed-components-well)
        - [Collections Cards in a Well](https://hs-colorful-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com/components/collections/collections-cards-well)
    - Traditional
        - [Collection with Mixed Components in a Well](https://hs-traditional-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com/components/collections-0/collection-mixed-components/collection-mixed-components-well)
        - [Collections Cards in a Well](https://hs-traditional-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com/components/collections-0/collections-cards-well)

### Private collections

1. In the case of the private collections, the test sites already include private pages with "Limited width" and "Full width" example private collections. In both [colorful](https://hs-colorful-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com/user/login) and [traditional](https://hs-traditional-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com/user/login) reference sites, log in and visit the following pages:
    -  Colorful
        - [Private Page Collection Cards Raised Uniform Stretch Limited Width](https://hs-colorful-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com/private-pages/private-page-collection-cards-raised-uniform-stretch-limited-width)
        - [Private Page Collection Cards Raised Uniform Stretch Full Width](https://hs-colorful-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com/private-pages/private-page-collection-cards-raised-uniform-stretch-full-width)
    - Traditional
        - [Private Page Collection Cards Raised Uniform Stretch Limited Width](https://hs-traditional-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com/private-pages/private-page-collection-cards-raised-uniform-stretch-limited-width-0)
        - [Private Page Collection Cards Raised Uniform Stretch Full Width](https://hs-traditional-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com/private-pages/private-page-collection-cards-raised-uniform-stretch-full-width)
5. In each site, confirm that the horizontal spacing between the well border are the content is the same (32px in traditional and 48px in colorful) for both the "Limited Width" and the "Full Width" versions.

Screenshot 2024-09-30 at 9 55 56 AM

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1639-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com
- https://hs-colorful-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com
- https://hs-traditional-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com
- https://english-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66fa24319936a61c2a90cfca

Visual Diffs:
- https://dashboard.tugboatqa.com/66fa24319936a61c2a90cfca/visualdiffs

**Review by mariannuar — APPROVED** [review]
@cienvaras Looks good!

**Comment by cienvaras** [comment]
@ahughes3 Ready for you!

**Comment by ahughes3** [comment]
@cienvaras 

1. Was the update applied to private collections and (regular) collections? If so can you update testing instructions for those cases as well?

2. As part of the task in ClickUp we also want to add help text to the field in private collections; I'm making a note in CLickUp but it should match the text that's on the field in the regular collection

`Applies when the page is full width. If the page includes a sidebar, this option will have no effect.`

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1639-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com
- https://hs-colorful-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com
- https://hs-traditional-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com
- https://english-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66fa24319936a61c2a90cfca

Visual Diffs:
- https://dashboard.tugboatqa.com/66fa24319936a61c2a90cfca/visualdiffs

**Comment by cienvaras** [comment]
@ahughes3 

> Was the update applied to private collections and (regular) collections? If so can you update testing instructions for those cases as well?

Yes, the styles are shared by both components. I updated the testing instructions

> As part of the task in ClickUp we also want to add help text to the field in private collections; I'm making a note in CLickUp but it should match the text that's on the field in the regular collection

Done. I added the help text for the collections in another PR, but forgot the private collections. It's fixed now.

**Review by ahughes3 — APPROVED** [review]

**Comment by joegl** [comment]
@cienvaras It looks like there's now a conflict based on the merged change in #1640

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1639-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com
- https://hs-colorful-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com
- https://hs-traditional-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com
- https://english-g9j9x8t9nkrxyklug7jf0vtaq10vfgaa.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66fa24319936a61c2a90cfca

Visual Diffs:
- https://dashboard.tugboatqa.com/66fa24319936a61c2a90cfca/visualdiffs

**Comment by cienvaras** [comment]
@joegl Conflicts fixed, ready to review again.

**Review by joegl — APPROVED** [review]

**Pull request merged**
