### PR TITLE
SHS-5811: Add logout button to sites

### PR DESCRIPTION
**Pull request by codechefmarc**
# READY FOR REVIEW

## Summary
- Adds a temporary `composer.json` change for adding a forked version of the `stanford_samlauth` module that adds logout button functionality. (This change needs to be reverted before merge!)
- Adds classes to the logout button to match login button

## Need Review By (Date)
2024-09-07

## Urgency
low

## Steps to Test
1. Login to the site as an admin
2. Visit the Block layout page Block page: `/admin/structure/block`
3. Click "Place block" in the footer region
4. Choose the "SAML SUNetID Logout Block"
5. Do not display the title, then click "Save Block"

Screenshot 2024-10-15 at 4 06 34 PM

6. Verify on the front-end, while logged in, that there is now a logout button

Screenshot 2024-10-15 at 4 05 15 PM

7. Click o the logout button and verify that it correctly logs you out of the site

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208463370275106

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1641-qtksbm9l06digqv9kfyizm9lbpogpcru.tugboatqa.com
- https://hs-colorful-qtksbm9l06digqv9kfyizm9lbpogpcru.tugboatqa.com
- https://hs-traditional-qtksbm9l06digqv9kfyizm9lbpogpcru.tugboatqa.com
- https://english-qtksbm9l06digqv9kfyizm9lbpogpcru.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66fc7cc6365d2bbbe5bab9dc

Visual Diffs:
- https://dashboard.tugboatqa.com/66fc7cc6365d2bbbe5bab9dc/visualdiffs

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1641-qtksbm9l06digqv9kfyizm9lbpogpcru.tugboatqa.com
- https://hs-colorful-qtksbm9l06digqv9kfyizm9lbpogpcru.tugboatqa.com
- https://hs-traditional-qtksbm9l06digqv9kfyizm9lbpogpcru.tugboatqa.com
- https://english-qtksbm9l06digqv9kfyizm9lbpogpcru.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66fc7cc6365d2bbbe5bab9dc

Visual Diffs:
- https://dashboard.tugboatqa.com/66fc7cc6365d2bbbe5bab9dc/visualdiffs

**Comment by codechefmarc** [comment]
@joegl - Adding you in here for review. Other PR for the forked repo is here: https://github.com/SU-SWS/stanford_samlauth/pull/21

**Comment by ahughes3** [comment]
@joegl I added a comment - https://github.com/SU-SWS/stanford_samlauth/pull/21#discussion_r1799737053 on the stanford_samlauth PR.

There was a comment that we needed clarification on: Since this is a "Login Block", it think it would be better to use a new block plugin.

@codechefmarc wasn't sure if this meant he needed to create a new block for logout as the original plan was to do everything in that block plugin.

I didn't know if it was more of a naming convention issue or a best practice/functionality issue. If the functionality works could updating the naming of the block to `SamlLoginLogutBlock` cover the concerns?

**Comment by ahughes3** [comment]
[Update from Mike](https://github.com/SU-SWS/stanford_samlauth/pull/21#discussion_r1799755707) - We can change the name of the file & class but, it's not an option to change the ID of the block plugin. This would cause cascading issues on every platform that uses the module and block.
Because the block id is `login`, it is best to create a `logout` block. you can almost copy the current block plugin and just reverse the access condition and display a logout button instead.

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1641-qtksbm9l06digqv9kfyizm9lbpogpcru.tugboatqa.com
- https://hs-colorful-qtksbm9l06digqv9kfyizm9lbpogpcru.tugboatqa.com
- https://hs-traditional-qtksbm9l06digqv9kfyizm9lbpogpcru.tugboatqa.com
- https://english-qtksbm9l06digqv9kfyizm9lbpogpcru.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66fc7cc6365d2bbbe5bab9dc

Visual Diffs:
- https://dashboard.tugboatqa.com/66fc7cc6365d2bbbe5bab9dc/visualdiffs

**Comment by codechefmarc** [comment]
@cienvaras - Updated this PR with the latest code to split the logout block into its own plugin and ready for review.

**Review by pookmish — CHANGES_REQUESTED** [review]
This doesn't add the new block. Please revise.
I've updated the `develop` branch dependencies. It how contains the logout block from stanford_samlauth.

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1641-zzqrp5ayck1ftlvplsrq7zhmr0mzn5ms.tugboatqa.com
- https://hs-colorful-zzqrp5ayck1ftlvplsrq7zhmr0mzn5ms.tugboatqa.com
- https://hs-traditional-zzqrp5ayck1ftlvplsrq7zhmr0mzn5ms.tugboatqa.com
- https://english-zzqrp5ayck1ftlvplsrq7zhmr0mzn5ms.tugboatqa.com
- https://history-zzqrp5ayck1ftlvplsrq7zhmr0mzn5ms.tugboatqa.com
- https://west-zzqrp5ayck1ftlvplsrq7zhmr0mzn5ms.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/674fbe52dab10e2ceed6dd64

Visual Diffs:
- https://dashboard.tugboatqa.com/674fbe52dab10e2ceed6dd64/visualdiffs

**Comment by codechefmarc** [comment]
This can be closed in favor of #1696 which adds the new logout button to existing sites.

**Pull request closed without merging**
