### PR TITLE
fix(shs-5091): adding a check for if a heading tag is already present

### PR DESCRIPTION
**Pull request by mndonx**
# READY FOR REVIEW

## Summary
This PR adds a check for if an `<h>` tag is already present before printing an `<h3>` wrapper for the View title. 

## Urgency
medium

## Steps to Test
1. Visit a page like https://bingschool.suhumsci.loc/news-events/bing-times
2. Ensure that there is no longer an HTML error on "2023 Issue" title (halfway down the page) where the template prints an open `<h3>` tag, self-closes, and then the `<h2>2023 Issue</h2>` prints after it. 

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by mndonx** [comment]
@cienvaras I just spent like 30 minutes trying to figure out how the title is being added to read "2023 Issue" (like, how is that H2 and the classes being added) and I still can't find it. I'd love to know so I can test it a little further. Can you point me in the right direction?

**Review by cienvaras — APPROVED** [review]
Works as expected!

**Comment by cienvaras** [comment]
@mndonx The title is being added using grouping. The nodes in the view are grouped by the "Bing Times Issue" field in the views format configuration:

Screenshot 2023-10-10 at 16 46 11

And, in the field settings, the output is being rewritten to add the `<h2>` and the class:

Screenshot 2023-10-10 at 16 47 25

**Comment by mndonx** [comment]
@cienvaras I appreciate you explaining that -- I couldn't find it anywhere!

**Pull request merged**
