### PR TITLE
SHS-5868: Uninstall admin login path module

### PR DESCRIPTION
**Pull request by cienvaras**
# READY FOR REVIEW

## Summary
- Follow up to [this comment](https://github.com/SU-HSDO/suhumsci/pull/1401#issuecomment-2341294896), adds an update hook to properly uninstall `admin_login_path` module. Will remove the module from `composer.json` in a follow-up PR to be added to a future release.

## Need Review By (Date)
10/23

## Urgency
medium

## Steps to Test
1. Visit `/admin/modules`, search for "admin login path" and confirm that the "Admin Login Path" module is disabled.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208572384688698

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1652-frhzlugwffqlcu9gyuuqbzwoepwawgm3.tugboatqa.com
- https://hs-colorful-frhzlugwffqlcu9gyuuqbzwoepwawgm3.tugboatqa.com
- https://hs-traditional-frhzlugwffqlcu9gyuuqbzwoepwawgm3.tugboatqa.com
- https://english-frhzlugwffqlcu9gyuuqbzwoepwawgm3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/670d5809536b1c1e4ec470e9

Visual Diffs:
- https://dashboard.tugboatqa.com/670d5809536b1c1e4ec470e9/visualdiffs

**Comment by cienvaras** [comment]
@ahughes3 Ready for you to review.

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1652-frhzlugwffqlcu9gyuuqbzwoepwawgm3.tugboatqa.com
- https://hs-colorful-frhzlugwffqlcu9gyuuqbzwoepwawgm3.tugboatqa.com
- https://hs-traditional-frhzlugwffqlcu9gyuuqbzwoepwawgm3.tugboatqa.com
- https://english-frhzlugwffqlcu9gyuuqbzwoepwawgm3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/670d5809536b1c1e4ec470e9

Visual Diffs:
- https://dashboard.tugboatqa.com/670d5809536b1c1e4ec470e9/visualdiffs

**Review by ahughes3 — APPROVED** [review]
Admin Login Path is disabled on the Tugboat preview sites ✅

**Comment by joegl** [comment]
@cienvaras 

1. Looks like there's a merge conflict to resolve with the database update hook.
2. We should also remove this line from the `su_humsci_profile.info.yml` https://github.com/SU-HSDO/suhumsci/blob/0f6d8dd060ad65297f61261803cd320dc0740a4f/docroot/profiles/humsci/su_humsci_profile/su_humsci_profile.info.yml#L55?

**Comment by cienvaras** [comment]
@joegl Thanks, done!

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1652-frhzlugwffqlcu9gyuuqbzwoepwawgm3.tugboatqa.com
- https://hs-colorful-frhzlugwffqlcu9gyuuqbzwoepwawgm3.tugboatqa.com
- https://hs-traditional-frhzlugwffqlcu9gyuuqbzwoepwawgm3.tugboatqa.com
- https://english-frhzlugwffqlcu9gyuuqbzwoepwawgm3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/670d5809536b1c1e4ec470e9

Visual Diffs:
- https://dashboard.tugboatqa.com/670d5809536b1c1e4ec470e9/visualdiffs

**Review by joegl — APPROVED** [review]
Awesome, thanks @cienvaras

**Pull request merged**
