### PR TITLE
SHS-5791: Update Stanford University brand bar link

### PR DESCRIPTION
**Pull request by mariannuar**
# READY FOR REVIEW

## Summary
Update Stanford University brand bar link

## Need Review By (Date)
09/04

## Urgency
medium

## Steps to Test
1.  Visit the Tugboat site
2. Confirm the link of the brand bar (at the top of the page) is now https://www.stanford.edu/

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208231439272377

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1618-kngg0sawy7ic38q8mao8mne7iqehss3k.tugboatqa.com
- https://hs-colorful-kngg0sawy7ic38q8mao8mne7iqehss3k.tugboatqa.com
- https://hs-traditional-kngg0sawy7ic38q8mao8mne7iqehss3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66d892aceb4136fc1c828ac0

Visual Diffs:
- https://dashboard.tugboatqa.com/66d892aceb4136fc1c828ac0/visualdiffs

**Review by cienvaras — APPROVED** [review]
@mariannuar Works as expected, thanks! Just removed a couple of extra unnecessary spaces.

@ahughes3 Ready for you to review.

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1618-kngg0sawy7ic38q8mao8mne7iqehss3k.tugboatqa.com
- https://hs-colorful-kngg0sawy7ic38q8mao8mne7iqehss3k.tugboatqa.com
- https://hs-traditional-kngg0sawy7ic38q8mao8mne7iqehss3k.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66d892aceb4136fc1c828ac0

Visual Diffs:
- https://dashboard.tugboatqa.com/66d892aceb4136fc1c828ac0/visualdiffs

**Review by ahughes3 — APPROVED** [review]
looks good!

**Review by joegl — APPROVED** [review]

**Pull request merged**
