### PR TITLE
HSD8-204 Start of circle.ci integration

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Set up integration with Circle.CI for automated testing
- Set up behat tests for site testing
- Set up phpunit test for module & config tests
- Added CI config split.

# Needed By (Date)
- asap

# Urgency
- kinda high

# Steps to Test
Mostly manual review
1. Review circle.ci tests
1. review config files and test files.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
Yo, why circle?

**Comment by pookmish** [comment]
¯\_(ツ)_/¯ taking a look at something different. And Lullabot had an article on it. https://www.lullabot.com/articles/continuous-integration-drupal-8-circleci

**Comment by pookmish** [comment]
I do like that you can have multiple tests at the same time and they show up separately here. It could make it for finding issues faster?

**Comment by sherakama** [comment]
Great, I'm putting you down to show your findings at the dev chat on the 23. Thanks for volunteering!

**Comment by pookmish** [comment]
This is a nice feature to turn on 
> we will automatically cancel any queued or running builds on a branch when a newer build is triggered on that same branch.

**Pull request merged**
