### PR TITLE
SHS-4652: Bug: hb-raised-cards utility classes are affecting Vertical Linked Cad styling

### PR DESCRIPTION
**Pull request by callinmullaney**
# READY FOR REVIEW

## Summary
- Fixes conflicts with `.hb-raised-cards` utility class with `hb-raised-cards--uniform-height` and `hb-stretch-vertical-linked-cards`

## Need Review By (Date)
3/20

## Urgency
low

## Steps to Test
1. Spin up both Colorful and Traditional for testing. The results for each will be slightly different.
2. Go to https://hs-colorful.suhumsci.loc/collections-cards and https://hs-traditional.suhumsci.loc/collections-cards
3. Click the "Layout" tab and "Configure" the main region that houses the cards. Add `hb-raised-cards hb-stretch-vertical-linked-cards hb-raised-cards--uniform-height` as your classes. Note both the "stretch" and "uniform" clases are added here. The results should look like: 
Screenshot from 2023-03-17 09-50-38
Screenshot from 2023-03-17 09-51-03

4. Edit the layout classes again but remove the "uniform" class. Results should be:
Screenshot from 2023-03-17 09-54-26
Screenshot from 2023-03-17 09-54-15

5. Edit the layout classes again but restore the "stretch" class and remove the "uniform" class. The results should be:
Screenshot from 2023-03-17 09-56-47
Screenshot from 2023-03-17 09-57-27

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by ryanhagerty** [comment]
@callinmullaney 

I'm seeing different things than the screenshots, and Traditional has some weirdness going on with it. Here's what I see (I'm using Chrome).

1. All three classes


1a

2. Removing the uniform class:


2a

3. Putting back the uniform class and removing stretch:


3a

**Review by ryanhagerty — CHANGES_REQUESTED** [review]
See comment with screenshots

**Comment by callinmullaney** [comment]
@ryanhagerty Can you pull my latest commit and re-test this? Looking into this further it looks like the stretch class was triggering a JS equalizer function. However, the equalizer function was applied to all cards on a page and not just cards within it's own collection. So the giant, single-column cards towards the bottom of the page were setting the height for all cards.

**Review by ryanhagerty — APPROVED** [review]
@callinmullaney I'm hitting approve because it looks good to me. Before merging, please take a look at the below screenshots for what I'm seeing. I think they line up, but the class naming doesn't 100% make sense to me, so I want to be sure this is the behavior you expected:

All three classes:

1a

Stretch removed:

2a

Uniform removed and readded stretch:

3a

**Pull request merged**
