### PR TITLE
SHS-5912: Improve link styles preview

### PR DESCRIPTION
**Pull request by cienvaras**
# READY FOR REVIEW

## Summary
- Change the layout of the CKEditor "Styles" dropdown, to show only one item per row and improve legibility of the preview.

## Need Review By (Date)
12/04

## Urgency
medium

## Steps to Test
1. Create a Flexible Page
2. In the text area component, add some text, headings, links, etc.
3. Try to apply some custom styles using the "Style" dropdown menu. Confirm that you see only one element per row and that the previews are legible. Confirm that you can apply and remove styles as expected.

Screenshot 2024-11-20 at 6 09 05 PM

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208819259769278

### CODE REVIEW

**Comment by ahughes3** [comment]
@cienvaras @joegl Tugboat is failing with this error:

Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. It is recommended that you run `composer update` or `composer update <package name>`.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires php >=8.3 but your php version (8.2.13) does not satisfy that requirement.
    
    
image

https://dashboard.tugboatqa.com/log/673eae1df67b7935927c2d64

**Comment by joegl** [comment]
@ahughes3 It looks like it was caching the previous docker image which was on PHP 8.2. I rebuilt the preview without a base and it is working now.

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1688-lpaybq02v8kmh3tn0cqcif2wqnrurrcr.tugboatqa.com
- https://hs-colorful-lpaybq02v8kmh3tn0cqcif2wqnrurrcr.tugboatqa.com
- https://hs-traditional-lpaybq02v8kmh3tn0cqcif2wqnrurrcr.tugboatqa.com
- https://english-lpaybq02v8kmh3tn0cqcif2wqnrurrcr.tugboatqa.com
- https://history-lpaybq02v8kmh3tn0cqcif2wqnrurrcr.tugboatqa.com
- https://west-lpaybq02v8kmh3tn0cqcif2wqnrurrcr.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/673f56c6513b09d01c53a0ac

**Review by ahughes3 — APPROVED** [review]
looks good!

**Review by pookmish — APPROVED** [review]
Simple fix :+1:

**Pull request merged**
