### PR TITLE
SHS-5691: New color palette for Traditional

### PR DESCRIPTION
**Pull request by mariannuar**
# READY FOR REVIEW

## Summary
Adds a new color palette for Traditional

## Need Review By (Date)
08/23

## Urgency
medium

## Steps to Test
1. Go to https://hs-traditional.suhumsci.loc/admin/appearance/settings/humsci_traditional
2. Check there's a new `Color Pairing` that is called 'Vireo' and select it
3. Explore the whole site (Views, Components, Homepage, Mixed pages)
4. Check everything looks good and similar to what's in the [design](https://www.figma.com/design/hOtD5MStjFIavUrWapHKHN/UX%2FDesign-Tickets-Work?node-id=1532-1468&t=dNtrb9yDISRi2SEc-4)
5. Please also check the footer and header looks as good when the dark variation is selected

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208108045225555

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1600-l8hrigmrk006r6ubwn2mp4fugzveljc3.tugboatqa.com
- https://hs-colorful-l8hrigmrk006r6ubwn2mp4fugzveljc3.tugboatqa.com
- https://hs-traditional-l8hrigmrk006r6ubwn2mp4fugzveljc3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66bcf3ef6c7d83449c0077f2

**Review by cienvaras — CHANGES_REQUESTED** [review]
@mariannuar Looks great! I just found a minor thing to fix and some inconsistencies with the designs that might be worth checking with Katy. Let me know if you have questions!

### To fix

The border of the secondary accordions is white on focus (this is probably an old issue, but this is a good opportunity to fix it):

Screenshot 2024-08-19 at 4 12 04 PM

### Inconsistencies

For this cases, please check with Katy (and with Tori if needed) if the difference is expected or if it's necessary to fix it. Keeping the current implementation is always preferred, because changing colors in specific components would introduce style overrides and we want to avoid them.

1. In the designs, the linked cards description background is "secondary highlight" but in the implementation is "tertiary reversed":
    Screenshot 2024-08-19 at 4 17 48 PM
2. There's a potential contrast issue in buttons/links inside a well collection:
    Screenshot 2024-08-19 at 4 21 07 PM
3. In the designs, the banner image with textbox button is black, but in the implementation color is "Secondary":
    Screenshot 2024-08-19 at 4 22 34 PM
4. Blockquotes in text areas are "gray dark" in the designs but "primary" in the implementation. Also confirm that the color for the testimonial quote is the right one (not in the designs)
    Screenshot 2024-08-19 at 4 25 20 PM

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1600-l8hrigmrk006r6ubwn2mp4fugzveljc3.tugboatqa.com
- https://hs-colorful-l8hrigmrk006r6ubwn2mp4fugzveljc3.tugboatqa.com
- https://hs-traditional-l8hrigmrk006r6ubwn2mp4fugzveljc3.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66bcf3ef6c7d83449c0077f2

**Comment by mariannuar** [comment]
@cienvaras Thank you for feedback! 

All of the inconsistencies are fixed now. For some of them Katy only had to update what it was in the design (vertical linked cards, blockquotes, and heros). For others we had to update the value of the `secondary` color and the`secondary-active` color (this one fixed the issue of the accordion that was only happening in this color palette).

Katy mentioned that testimonials will use `secondary` and blockquotes inside text-areas will use `primary`, as it is already implemented.

Let me know if you find something else. Thanks!

**Review by cienvaras — APPROVED** [review]
@mariannuar Thanks for the fixes and for checking with Katy. Everything looks great 🚀

**Pull request merged**
