### PR TITLE
SHS-5877: Editors can create anchor links to Colorbands

### PR DESCRIPTION
**Pull request by cienvaras**
# READY FOR REVIEW

## Summary
- Adds an `id` to the container of colorband paragraphs

## Need Review By (Date)
10/23

## Urgency
medium

## Steps to Test
1. Visit a page with "Colorband" components (or create a new one). You can use one of the following:
    - https://hs-colorful-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com/components/color-bands
    - https://hs-traditional-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com/components/color-bands
2. Inspect the page source code and search for `ptype-hs-clr-bnd`. This class is added to the colorband component wrapper `div`. You should also see in the `div` an `id` with the format `component-XYZ` (where `XYZ` is a unique numerical ID):
    Screenshot 2024-10-15 at 11 43 25 AM
3. Visit any other flexible page and search for other types of components. Confirm that the `id` is not present in any case. You can search for `ptype-` to find the component wrapper `div` elements. 

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208572389505173

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1653-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com
- https://hs-colorful-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com
- https://hs-traditional-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com
- https://english-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/670d62bd536b1c1e4ec532bc

Visual Diffs:
- https://dashboard.tugboatqa.com/670d62bd536b1c1e4ec532bc/visualdiffs

**Comment by cienvaras** [comment]
@ahughes3 Ready for you to review.

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1653-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com
- https://hs-colorful-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com
- https://hs-traditional-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com
- https://english-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/670d62bd536b1c1e4ec532bc

Visual Diffs:
- https://dashboard.tugboatqa.com/670d62bd536b1c1e4ec532bc/visualdiffs

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1653-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com
- https://hs-colorful-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com
- https://hs-traditional-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com
- https://english-upkqlcwztqtvm3dptlfkdwwrmvrflxy6.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/670d62bd536b1c1e4ec532bc

Visual Diffs:
- https://dashboard.tugboatqa.com/670d62bd536b1c1e4ec532bc/visualdiffs

**Review by ahughes3 — APPROVED** [review]
looks good!

**Review by joegl — APPROVED** [review]

**Pull request merged**
