### PR TITLE
SHS-5568: Allow editors to select style on Accordion component

### PR DESCRIPTION
**Pull request by hectorlj**
# READY FOR REVIEW

## Summary
Adds `Style` select to allow editors to apply the `hb-accordion-secondary` class to Accordion components

## Steps to Test
1. Create a new flexible page
2. Add two Accordion components
3. On one of the two components set the `Style` select to `Secondary`
4. Save the new page
5. The Accordion component with the `Style` select set to `Secondary` should now be using the `Secondary` style
6. The Accordion component with the `Style` select set to `Default` should use the default style

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by cienvaras** [comment]
@hectorlj Can you please update the code so the `hb-accordion-secondary` class is added to the `attributes` variable of the `<details>` element and remove the wrapper `<div>`? I'll need to update the styles anyways because currently the  `hb-accordion-secondary` class needs to be completely outside of the paragraph element. Thanks!

**Comment by cienvaras** [comment]
@hectorlj Thanks! I updated the CSS and it's working great. Just a couple of extra things I missed in my initial review:
- Can you please add an update hook to set all existing accordions style to "Default"
- Can you please confirm that the tests fails are not related with these changes? I don't think so, but better be on the safe side.

**Comment by hectorlj** [comment]
@cienvaras Looks like the menu tests are the culprits, but we're not touching any menu stuff here. Sometimes the tests will pass if rerun so I'm thinking it's a time out issue or something along those lines.

**Review by cienvaras — APPROVED** [review]
Looks good, thanks! 🚀

**Pull request merged**
