### PR TITLE
shs-81: bug fix for traditional layered slider at large screen size

### PR DESCRIPTION
**Pull request by ryanhagerty**
## Summary
This fixes a bug with the layered hero slider in a collection of two at large screen sizes in the traditional theme.

## Steps to Test
1. Create a new page. In the main region add a collection of two. Both of these items should be the Hero Layered Slider option.
2. Make sure the theme is Traditional. 
3. View the page at greater than `1500px`. Notice that the arrows for the slider are not off the box. 
4. Check to make sure this doesn't break a single layered hero slider (non collection)
5. Check to make sure this doesn't affect the colorful theme (this should only affect traditional - there's a separate bug for colorful).

## Screenshots
Screen Shot 2022-08-15 at 12 43 25 PM

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1160-dzyb8pxtlea0ltskzw9k5udtcrdkw5vo.tugboatqa.com
- https://hs-colorful-dzyb8pxtlea0ltskzw9k5udtcrdkw5vo.tugboatqa.com
- https://hs-traditional-dzyb8pxtlea0ltskzw9k5udtcrdkw5vo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62fa787c7e6c3f16dad8dbd7

**Review by callinmullaney — CHANGES_REQUESTED** [review]
@ryanhagerty This resolves the bug for sliders that appear as 2 and 3 items in a row. However, if I set this back to 1 item per row it now introduces the same bug to this setting. See screenshot.
Screenshot from 2022-08-16 10-48-10

**Comment by ryanhagerty** [comment]
@callinmullaney Should be good now. I tested with one slider in a collection and one outside of a collection.
Screen Shot 2022-08-16 at 3 29 42 PM

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1160-dzyb8pxtlea0ltskzw9k5udtcrdkw5vo.tugboatqa.com
- https://hs-colorful-dzyb8pxtlea0ltskzw9k5udtcrdkw5vo.tugboatqa.com
- https://hs-traditional-dzyb8pxtlea0ltskzw9k5udtcrdkw5vo.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62fa787c7e6c3f16dad8dbd7

**Review by callinmullaney — APPROVED** [review]
@ryanhagerty Looks good to me 👍

**Pull request merged**
