### PR TITLE
HSD8-1707: Removed edit button from default people view

### PR DESCRIPTION
**Pull request by sethprime**
# READY FOR REVIEW

## Summary
Removed edit button from default people view  config to resolve button displaying to anonymous users.
[HSD8-1707 | Edit button is viewed when logged out prior to cache clearing](https://stanfordits.atlassian.net/browse/HSD8-1707)

## Urgency
Low

## Steps to Test
1. Pull changes and import the updated configuration, views.view.hs_default_people.yml.
2. Verify that the Default People view's People list link, and People list link (grouped) blocks to not have a link to edit content in their Fields section.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1701-cyw8hkpbfsthbhhbxb6hceuceaawqukb.tugboatqa.com
- https://hs-colorful-cyw8hkpbfsthbhhbxb6hceuceaawqukb.tugboatqa.com
- https://hs-traditional-cyw8hkpbfsthbhhbxb6hceuceaawqukb.tugboatqa.com
- https://english-cyw8hkpbfsthbhhbxb6hceuceaawqukb.tugboatqa.com
- https://history-cyw8hkpbfsthbhhbxb6hceuceaawqukb.tugboatqa.com
- https://west-cyw8hkpbfsthbhhbxb6hceuceaawqukb.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/676350975a118331c6fb72b7

Visual Diffs:
- https://dashboard.tugboatqa.com/676350975a118331c6fb72b7/visualdiffs

**Review by pookmish — APPROVED** [review]
When you create the PR, make sure to use the release branch as the base to merge into.

**Comment by ahughes3** [comment]
@pookmish once this is rolled out will this only update the default view for sites going forward or would it update existing views? Want to prepare to see what type of work we will need to do on our end.

**Comment by pookmish** [comment]
@ahughes3 , It will update only the existing "Default" view for new and existing sites. But it won't make any changes to any custom views which is probably 99% (if not 100%) displays

**Pull request merged**
