### PR TITLE
feat: Lando integration for local development

### PR DESCRIPTION
**Pull request by callinmullaney**
# READY FOR REVIEW

## Summary
Updates the old lando setup with a more module/extendable approach for multisites.
Updates setup documentation

## Need Review By (Date)
TBD

## Urgency
high

## Steps to Test
1. Review the README documentation in `/lando/README.md` and follow the setup steps. Note: if you are using an ARM-based Mac you will need to follow additional setup steps as there are known compatibility issues with lando/docker and the M1/M2 Macs.
2. Verify you can sync and run multiple site's at once

### CODE REVIEW

**Comment by callinmullaney** [comment]
@marcb4k @pookmish I'm tagging you both here to verify the updates to the lando integration for local development. The setup should be pretty smooth for x86-based machines but there are additional steps for the newer Macs to consider.

**Comment by codechefmarc** [comment]
@callinmullaney - I can actually get about 25 sites to work now, which is amazing. I haven't tried past that yet. A part of that is a LOT of lando stop/poweroff/rebuild as sometimes it needs it a few times to actually work and make URL's green.

However, I am running into that [Composer issue with the allow-plugins](https://github.com/SU-HSDO/suhumsci/pull/1141). I updated to Composer 2.4.0 and I'm still having the same issue - array_merge(): Expected parameter 1 to be an array. 

Therefore, I can't install anything with Composer, including BLT, so I can't actually spin up a site. @pookmish - do you have a suggestion to fix?

**Comment by callinmullaney** [comment]
@marcb4k Per our slack discussion and further testing I updated the `default.lando.yml` file to specify composer 2.4.0 which fixes the bug you were running into. Let me know if you run into other issues.

**Comment by codechefmarc** [comment]
Ok, was successfully able to test 5 sites today, worked great. Composer issue has been fixed. Also, pulled DB's for 2 of the 5 sites (colorful and music) and was able to get them both working. I say this is ready to go from my end. Thanks!

**Review by codechefmarc — APPROVED** [review]
Tested this yesterday and added a comment there. Approving.

**Pull request merged**
