### PR TITLE
SHS-43: Contrast failures on pill on certain color palettes

### PR DESCRIPTION
**Pull request by Rain-kanyini**
# READY FOR REVIEW

## Summary
Changed the global value of the `hb-pill` to fix contrast errors.

image

## Need Review By (Date)
Whenever anyone is free

## Urgency
This ticket was in the backlog

## Steps to Test
1.  Go [here](http://sparkbox-sandbox.suhumsci.loc/courses/honors-thesis-research/12) run a tool to test for contrast. I personally used the WAVE evaluation tool (it is a browser addon)
2. Ensure that these two pills, do not have contrast errors:

image

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Review by mickey4k — APPROVED** [review]
I see the change in the browser and it passes color contrast.  HOWEVER, it passed color contrast prior to the change too. (Unless they're going for AAA compliance which is unlikely.)  Not sure who tested what and how so might need to check if there was another pill that actually didn't pass AA.  

Before change:
Screenshot from 2022-05-25 21-24-19

After change:
Screenshot from 2022-05-25 21-32-56

**Comment by mickey4k** [comment]
Additional comment.  I see a change only in an scss file.  Depending on the build process, that might be all that's needed.  I'm not sure how this site is built.  You may need to build the theme to create and commit a .css file also.  I'd check with Ryan on it.

**Review by mickey4k — CHANGES_REQUESTED** [review]
Looking at [Ryan's PR](https://github.com/SU-HSDO/suhumsci/pull/1125/files), it looks like the css files are needed.  Setting this back to needs work.  Sorry!!!

**Comment by Rain-kanyini** [comment]
> Looking at [Ryan's PR](https://github.com/SU-HSDO/suhumsci/pull/1125/files), it looks like the css files are needed. Setting this back to needs work. Sorry!!!

@mickey4k Thank you for catching that! I believe that I have now added the appropriate css files :)!

It's also odd that the pills were originally passing the contrast test, for me they weren't? I was using the WAVE tool, and perhaps its more picky than it needs to be?

**Comment by ryanhagerty** [comment]
Closing this PR for a couple reasons:
* We don't want to change the global mixin color (this is a color specific instance)
* After recreating the screenshot, it passes accessibility contrast (like Mickey confirmed above).

**Pull request closed without merging**
