### PR TITLE
Image styles fix

### PR DESCRIPTION
**Pull request by bryanbraun**
# READY FOR REVIEW

Please test thoroughly. @kaseybon, can you do a full review, and then once you approve, let's have @pookmish look before it gets merged.

> Can we switch the new stanford_image_large and stanford_image_medium to the scaled versions and rename the square versions stanford_image_[size]_square?

(see https://sparkbox.atlassian.net/browse/STN-264 for more details)

## Need Review By (Date)
asap

## Urgency
'Medium'

## Steps to Test
1. Pull down this branch
2. Import all the configuration for these image styles and view modes.
    - `lando drush @mysite.local config-import`
    - Warning: this could impact your local environment, if you have different local config.
3. Go to a basic page, create a Text Area Paragraph, insert each of the image styles and confirm that they work as expected (including with floats, etc)
4. Check for regressions.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

### CODE REVIEW

**Review by pookmish — APPROVED** [review]
Interesting thing to note, we did very similar things in the campus wide product.

**Comment by pookmish** [comment]
Dont worry about the failing tests right now. I've got a fix for that in https://github.com/SU-HSDO/suhumsci/pull/518

**Comment by kaseybon** [comment]
@pookmish thank you for the approval! We're still doing some testing on our end. I'll let you know once we're done.

**Comment by kaseybon** [comment]
@bryanbraun everything looks good but I have one question. The image I first uploaded wasn't quite large enough to match the large and xl sizes. For the scaled images I just got the full sized image:
Screen Shot 2020-03-12 at 6 43 25 PM

For the square sizes the images were then scaled up and cropped:
Screen Shot 2020-03-12 at 6 43 47 PM

Is this expected?

---

Note: I did test with an image that was large enough to be scaled down to large/xl sizes and they are re-sized as expected.

**Comment by bryanbraun** [comment]
@kaseybon this behavior is apparently called upscaling, and it's a setting that exists for the rectangular image styles, [as shown here](https://user-images.githubusercontent.com/1256329/76638391-bfd62f80-6522-11ea-806f-4599cb720eef.png):

Our new rectangular image styles follow the same upscaling behavior that was in place for the previous image styles: Upscaling is not allowed. That's why the rectangular images aren't resized larger than their original dimensions.

This upscaling setting [is NOT available for image styles using focal-point image styles](https://user-images.githubusercontent.com/1256329/76639144-00827880-6524-11ea-8ff0-a3df73f92513.png). That means our square image styles (which use focal point) have upscaling enabled, and we can't disable it. [There is an open issue on the focal point module to add support for disabled upscaling](https://www.drupal.org/project/focal_point/issues/3048398), but no work has been done on it.

We should show this to H&S and make sure they're ok with this behavior before merging.

**Review by kaseybon — APPROVED** [review]

**Comment by kaseybon** [comment]
H&S has approved the current image behavior so I have added my approval to the PR. @pookmish this is ready for you again.

**Pull request merged**
