### PR TITLE
shs-890 - apply the fixed image/text height to mobile

### PR DESCRIPTION
**Pull request by ryanhagerty**
## Summary
This adjusts mobile/tablet hero slider carousels to have fixed heights similar to how it is already employed on desktop.
This is accomplished by making mobile/tablet images `object-fit: cover` and by removing the screen size check in the pre-existing JS that applies inline styles. 

## Steps to Test
1. After pulling down this page, create a flexible page.
2. Add a `Hero (Layered) - Slider` to the Full-width region. Add two or three slides with different image aspect ratios and with different text lengths.
3. Save and scroll through the slider at mobile to observe that: the image takes the same height and the box container for the title/text takes the same height across slides.
4. Refresh and do the same for desktop as due diligence to make sure it doesn't break pre-existing functionality. 

## Screenshots
Screen Shot 2022-08-09 at 2 05 09 PM

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1159-ffpgbkpyywywlusfkajxawx6cupgfycx.tugboatqa.com
- https://hs-colorful-ffpgbkpyywywlusfkajxawx6cupgfycx.tugboatqa.com
- https://hs-traditional-ffpgbkpyywywlusfkajxawx6cupgfycx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f2a20219770b441a5750e4

**Review by callinmullaney — CHANGES_REQUESTED** [review]
@ryanhagerty I ran several tests of this PR on the hs-colorful and hs-traditional sites. From what I can see this is meeting acceptance criteria except for a particular instance. If I add a title/caption to a slide but not another slide in the sequence then there is a height shift. 

From the examples in the ticket it appears that this might be an edge case but maybe addressing this now is still in-scope for this ticket.

**Review by callinmullaney — APPROVED** [review]
:sandwich:

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1159-ffpgbkpyywywlusfkajxawx6cupgfycx.tugboatqa.com
- https://hs-colorful-ffpgbkpyywywlusfkajxawx6cupgfycx.tugboatqa.com
- https://hs-traditional-ffpgbkpyywywlusfkajxawx6cupgfycx.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62f2a20219770b441a5750e4

**Pull request merged**
