### PR TITLE
shs-55: edit breakout box wysiwyg class and color

### PR DESCRIPTION
**Pull request by ryanhagerty**
## Summary
This changes the 'breakout box' WYSIWYG style with a new class `hs-breakout-box` and changes the color from the previous setting for well to `spotlight`. 

## Steps to Test
1. Import the config and create a new flexible page.
2. Add a text component, add some text, highlight it and add the 'Breakout Box' style (screenshot below).
3. You should be able to add this class and have it applied for all text formats _except_ Minimal HTML.
4. View the page and verify it's using the theme's 'spotlight color'
5. Verify the above works for the Traditional theme as well. 

## Screenshots
Screen Shot 2022-09-19 at 9 46 49 AM

Screen Shot 2022-09-19 at 9 47 02 AM

### CODE REVIEW

**Comment by ryanhagerty** [comment]
I don't see the `fk-stnfd-sprint-9` branch anymore?

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1181-1jvkfka6sc4cqrsjcbsl54qddfpxqavt.tugboatqa.com
- https://hs-colorful-1jvkfka6sc4cqrsjcbsl54qddfpxqavt.tugboatqa.com
- https://hs-traditional-1jvkfka6sc4cqrsjcbsl54qddfpxqavt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63287478aef88bc4d6cf48af

**Review by callinmullaney — APPROVED** [review]
@ryanhagerty This looks good to me. Can you make sure to add this new class to the docs here: https://github.com/SU-HSDO/suhumsci/blob/develop/docroot/themes/humsci/humsci_basic/docs/utility-classes.md#wysiwyg-platform-wide-text-area-classes ?

**Comment by ryanhagerty** [comment]
@callinmullaney Thanks Callin - updated

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1181-1jvkfka6sc4cqrsjcbsl54qddfpxqavt.tugboatqa.com
- https://hs-colorful-1jvkfka6sc4cqrsjcbsl54qddfpxqavt.tugboatqa.com
- https://hs-traditional-1jvkfka6sc4cqrsjcbsl54qddfpxqavt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63287478aef88bc4d6cf48af

**Pull request merged**
