### PR TITLE
Four Kitchens Release - Sprint 56

### PR DESCRIPTION
**Pull request by cienvaras**
# READY FOR REVIEW

## Summary

- SHS-5692 - Implementation: New Spotlight design for Colorful and Traditional
- SHS-5772 - Regression: External Links on Postcards are wrong color
- SHS-5629 - Editors can more easily edit a caption

## Need Review By (Date)
08/14

## Urgency
medium

### SHS-5692

1. In Colorful and Traditional
2. Create a flexible page for Spotlights using the new style "Expanded" with the following considerations:
    - Using different backgrounds (default or gray)
    - Using different heights (short or tall)
    - Aligning the image on the left or right side
    - Spolights in sliders and collections
    - Nested in a colored background (collections with the background option selected)
3. Confirm that they look as expected in both sites: [Traditional Design](https://www.figma.com/design/hOtD5MStjFIavUrWapHKHN/UX%2FDesign-Tickets-Work?node-id=2308-2584&t=crtPAvWNHYT7bAob-4) / [Colorful Design](https://www.figma.com/design/hOtD5MStjFIavUrWapHKHN/UX%2FDesign-Tickets-Work?node-id=1731-218&t=crtPAvWNHYT7bAob-4)
4. Please, pay special attention to Warbler color pairing in Traditional
5. Check the "Classic" or default Spotlight style is unchanged

### SHS-5772

1. Go to the following sites
    - https://economics.suhumsci.loc/undergraduate/honors-program (postcards, Colorful Lake)
    - https://chemistry.suhumsci.loc/about/culture (view Traditional, Cardinal)
    - https://archaeology.suhumsci.loc/ (publications view, Colorful Ocean)
    - https://statistics.suhumsci.loc/industrial-affiliates/industrial-affiliates-program (postcards, Colorful Mountain)
2. Check that the external links are now looking as expected (colour is black text with bottom border)
3. On Colorful and Traditional
4. Go to `/components/collections-cards/collections-postcards`
5. Edit some of them and add internal and external links for all the variations of Postcards (except the vertical linked card)
6. Check the look the same as expected
7. Also test everything in multiple colour palettes (pay attention to the Warbler color pairing in Traditional themes)

### SHS-5629

1. Login to the site 
2. Edit the homepage or a page that has a "Banner image(s) with partial overlay and text

Screenshot 2024-07-19 at 3 48 55 PM

3. Click "Edit" in the "Banner image(s) with partial overlay and text" paragraph

Screenshot 2024-07-19 at 3 49 07 PM

4. Click "Edit" on one of the "Banner image with overlay and text" paragraphs

Screenshot 2024-07-19 at 3 49 16 PM

5. Verify that there's now a pencil icon in addition to the "X" icon on top of the Image media

Screenshot 2024-07-19 at 3 49 22 PM

6. Click the pencil icon
7. Verify that a modal pops up that has the media edit form for that image

Screenshot 2024-07-19 at 3 49 29 PM

8. Change the text in the "Caption/Credit" text area
9. Save the media in the modal
10. Save the page
11. Verify that the caption text on the slide that was edited has now changed

DEMO:
https://www.loom.com/share/a259e04858f94220aa10e26d36fe54d5?sid=d5197c3b-c4fc-4cc6-a0e5-3f53b77afd7a

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Review by joegl — COMMENTED** [review]
Is the patch which allows media edits in a modal going to affect the work @codechefmarc did in https://github.com/fourkitchens/stanford_migrate/pull/2? It's a big patch which adds functionality that doesn't exist. I'm not sure how I feel about it.

**Comment by codechefmarc** [comment]
@joegl - I just tested locally both PR's together - the changes for `stanford_migrate` and the composer patches to allow media editing in a modal and both work together just fine. @cienvaras

**Comment by codechefmarc** [comment]
@joegl - Though my test did work, I did get some errors applying patches (not related) on my local:
```
- Applying patches for drupal/field_group
    https://www.drupal.org/files/issues/2023-04-24/2969051-99.patch (https://www.drupal.org/project/field_group/issues/2969051)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2023-04-24/2969051-99.patch
    https://www.drupal.org/files/issues/2023-04-07/2787179-highlight-html5-validation-85.patch (https://www.drupal.org/project/field_group/issues/2787179)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2023-04-07/2787179-highlight-html5-validation-85.patch

  - Applying patches for drupal/paragraphs
    https://www.drupal.org/files/issues/2021-05-06/paragraphs-2895561-32.patch (https://www.drupal.org/project/paragraphs/issues/2895561)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2021-05-06/paragraphs-2895561-32.patch

  - Applying patches for drupal/redirect
    https://www.drupal.org/files/issues/2020-12-14/validation-issue-3057250-29.patch (https://www.drupal.org/project/redirect/issues/3057250)
   Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2020-12-14/validation-issue-3057250-29.patch
    patches/contrib/redirect-loops.patch (https://www.drupal.org/project/redirect/issues/3018897)
```

**Comment by joegl** [comment]
> @joegl - Though my test did work, I did get some errors applying patches (not related) on my local:
> 
> ```
> - Applying patches for drupal/field_group
>     https://www.drupal.org/files/issues/2023-04-24/2969051-99.patch (https://www.drupal.org/project/field_group/issues/2969051)
>    Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2023-04-24/2969051-99.patch
>     https://www.drupal.org/files/issues/2023-04-07/2787179-highlight-html5-validation-85.patch (https://www.drupal.org/project/field_group/issues/2787179)
>    Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2023-04-07/2787179-highlight-html5-validation-85.patch
> 
>   - Applying patches for drupal/paragraphs
>     https://www.drupal.org/files/issues/2021-05-06/paragraphs-2895561-32.patch (https://www.drupal.org/project/paragraphs/issues/2895561)
>    Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2021-05-06/paragraphs-2895561-32.patch
> 
>   - Applying patches for drupal/redirect
>     https://www.drupal.org/files/issues/2020-12-14/validation-issue-3057250-29.patch (https://www.drupal.org/project/redirect/issues/3057250)
>    Could not apply patch! Skipping. The error was: Cannot apply patch https://www.drupal.org/files/issues/2020-12-14/validation-issue-3057250-29.patch
>     patches/contrib/redirect-loops.patch (https://www.drupal.org/project/redirect/issues/3018897)
> ```

Yea recent updates to these modules breaks the patches (we've seen this in other stacks). I'll be fixing those later. However, a `composer install` should still work.

**Review by joegl — APPROVED** [review]

**Pull request merged**
