### PR TITLE
HSD8-1658: Added English site preview to Tugboat

### PR DESCRIPTION
**Pull request by ahughes3**
adding english as a preview option

# READY FOR REVIEW

## Summary
_[briefly summarize the changes here]_

## Need Review By (Date)
_['10/30', 'asap', etc.]_

## Urgency
_['low', 'medium', 'high', etc.]_

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by joegl** [comment]
@pookmish We're trying to add another site to tugboat previews (`english`) but running into an issue where it says the database doesn't exist.

**Comment by pookmish** [comment]
@joegl, I'm wonder if it's kinda like a "cache" issue. The preview is building from `develop` as the base. So I'm thinking it's not running the mysql commands. I rebuilt the preview without a "base" preview and it seems to be running those commands.

**Comment by joegl** [comment]
> @joegl, I'm wonder if it's kinda like a "cache" issue. The preview is building from `develop` as the base. So I'm thinking it's not running the mysql commands. I rebuilt the preview without a "base" preview and it seems to be running those commands.

Yea the logs didn't show some commands and we noticed it was building from develop. How did you rebuild without the base? We probably just have to merge it.

**Comment by pookmish** [comment]
I had to click "Delete" and then I was able to rebuild it without a base preview.

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1614-h6kipo90jc1xs9lf5dijvv0pglvufwoi.tugboatqa.com
- https://hs-colorful-h6kipo90jc1xs9lf5dijvv0pglvufwoi.tugboatqa.com
- https://hs-traditional-h6kipo90jc1xs9lf5dijvv0pglvufwoi.tugboatqa.com
- https://english-h6kipo90jc1xs9lf5dijvv0pglvufwoi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66e072ede4ba33c22047996e

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1614-h6kipo90jc1xs9lf5dijvv0pglvufwoi.tugboatqa.com
- https://hs-colorful-h6kipo90jc1xs9lf5dijvv0pglvufwoi.tugboatqa.com
- https://hs-traditional-h6kipo90jc1xs9lf5dijvv0pglvufwoi.tugboatqa.com
- https://english-h6kipo90jc1xs9lf5dijvv0pglvufwoi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66e072ede4ba33c22047996e

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1614-h6kipo90jc1xs9lf5dijvv0pglvufwoi.tugboatqa.com
- https://hs-colorful-h6kipo90jc1xs9lf5dijvv0pglvufwoi.tugboatqa.com
- https://hs-traditional-h6kipo90jc1xs9lf5dijvv0pglvufwoi.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66e072ede4ba33c22047996e

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1614-a4pyuozrswth48naxskbteggskuykkjc.tugboatqa.com
- https://hs-colorful-a4pyuozrswth48naxskbteggskuykkjc.tugboatqa.com
- https://hs-traditional-a4pyuozrswth48naxskbteggskuykkjc.tugboatqa.com
- https://english-a4pyuozrswth48naxskbteggskuykkjc.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f324d96f1e8632c5b7b95c

**Review by joegl — APPROVED** [review]

**Pull request merged**
