### PR TITLE
Feat(STN-896): add js linting

### PR DESCRIPTION
**Pull request by pebutler3**
# READY FOR REVIEW

## Summary
Identified as part of the strategy to increase stability & confidence in the application, JavaScript linting needed to be added. With this PR we achieve:

- linting for `humsci_basic`
- Webpack upgrades
- resolution of newly discovered lint errors.

## Need Review By (Date)
_asap_

## Urgency
medium

## Steps to Test
1. run `npm i` from `docroot/themes/humsci/humsci_basic`
2. run `npm run start` to confirm base theme builds as expected
3. run `npm run lint:js` to confirm eslint task runs independently of ☝️. You may need to edit a javaScript file to cause an error.
4. With an error present in your JS, once again run `npm run start` to confirm that a lint error causes the build to fail. Functionally speaking, all the code should work exactly the same as it did prior to the PR.
5. Switch between themes and test between different components that rely upon javaScript.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

### CODE REVIEW

**Comment by rkelbel** [comment]
@pebutler3 There is a failing acceptance test for Private Collections in the ParagraphsCest, I've rerun it and hit the same error. I don't see anything in what you've pushed up that should be causing that paragraph test to suddenly fail.

Can you rebase with the Sparkbox Sprint branch and see if the new commits in the release will fix this error?

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr991-mewvhdmbb9r3pdiylh0riaopilneaupu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61831009e368659b86349f40

**Comment by rkelbel** [comment]
This is good to go and I am good to approve this and merge, but want to verify we don't have JS rollbacks for hotfix before merging.

**Review by rkelbel — APPROVED** [review]
This looks good to me. 🥇 
thumbs up

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr991-mewvhdmbb9r3pdiylh0riaopilneaupu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61831009e368659b86349f40

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr991-mewvhdmbb9r3pdiylh0riaopilneaupu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61831009e368659b86349f40

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr991-mewvhdmbb9r3pdiylh0riaopilneaupu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61831009e368659b86349f40

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr991-mewvhdmbb9r3pdiylh0riaopilneaupu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61831009e368659b86349f40

**Pull request merged**
