### PR TITLE
Feat(STN-858):  private collections styling

### PR DESCRIPTION
**Pull request by pebutler3**
# READY FOR REVIEW

## Summary
Locate references to classes specifically targeting Collections (`.ptype-hs-collection`, `.field-hs-page-components`) and/or classes that are represented differently between public/private collections. The 2 shown above were all I was able to locate and were cases where I simply added the private collection class to the list (`.ptype-hs-priv-collection`, `.field-hs-priv-page-components`).

### Notes:
I do not know if  `su_humsci_theme` gets updates, but I added to it in this case for completeness. I am open to dropping this commit if it is unnecessary.

## Issue
[STN-858](https://sparkbox.atlassian.net/browse/STN-858)

## Urgency
_Medium_

## Steps to Test
Testing this can likely be time-consuming, though the amount of components available in a private collection are fairly limited. I will include some screenshots displaying private vs. public collections. The only difference I was able to find was that Private collections did not have the correct spacing that `ptype-hs-collection` was receiving.
1.) Create private page
2.) Create public page
3.) Add Collection(s) to private page and utilize all the available components.
4.) Repeat step #3 for your public page.
5.) Compare the 2
6.) Repeat process for unchecked theme.
7.) Insert any other testing methods you see fit.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

### CODE REVIEW

**Comment by pebutler3** [comment]
## Before
screenshot-before-spacing

## After
screenshot-after-spacing

**Comment by pebutler3** [comment]
## Public
public_h s

## Private
private_h s

**Comment by rkelbel** [comment]
So the styling looks accurate on Private Text Area's, Timelines and Postcards within Private Collections.

However on the admin side it seems like some configurations might be inaccurate, I'm not sure if we want to handle this or Mike needs to.. It's also possible this is just appearing on my local and not on yours, so please let me know if this is inaccurate.

Color Bands should probably not be available to the Private Collection options:

Screen Shot 2021-09-14 at 9 10 23 PM

It looks wonky if it is used, I'm assuming this shouldn't be an option.
colorband

I also noticed that the "Items Per Row" option doesn't default to "1" and has a "none" option which should probably not be there:
Screen Shot 2021-09-14 at 9 10 33 PM

Let me know if you see these issues in the configuration as well.

The styling looks accurate to the public collections, but we may want to surface this configuration if it's wrong.

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr958-hf9hfi1mzfppdiyrbqruivjlcwdxfp0d.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614215e3d7000a9cd4418d06

Visual Diffs:
- https://dashboard.tugboat.qa/614215e3d7000a9cd4418d06/visualdiffs

**Review by rkelbel — APPROVED** [review]
Nice work Paul!

Here is your reward:
schrute buck

**Comment by pebutler3** [comment]
> Nice work Paul!
> 
> Here is your reward:
> schrute buck

Holy Mackerel, you get me.

**Pull request merged**
