### PR TITLE
STN-527 : External Secondary Navigation Link Styles

### PR DESCRIPTION
**Pull request by heatherdesigns**
# READY FOR REVIEW

## Summary
Update styles for external links in the secondary navigation to look the same as the other regular secondary navigation links.

## Need Review By (Date)
7/20/2020

## Urgency
low

## Steps to Test
1. In your CLI, run `npm run test` and confirm all our tests pass.
2. To review this PR you will need an external link in the secondary navigation. You can either sync with the staging environment, or follow these steps to add one to your local environment:
* In the Drupal admin panel, go to Structure > Menus
* In the menu list, find `Main navigation` and click on `Edit Menu`
* On the `Edit menu Main Navigation` page, click on `Add link`
* On the `Add menu link` page
    * Find the `Menu link title` form field and enter `Test External Link`
    * Find the `Link` form field and enter `https://google.com`
    * Find `Parent link` and select `--QA`
    * Click `Save`
3. Go to any page on the site with a secondary navigation. For example: http://sparkbox-sandbox.suhumsci.loc/qa/qa-text-area
4. Verify the external link in the secondary navigation has the same styling as the other links. Confirm the hover and focus states of the external link are the same as well.
5. Confirm the external link fix also works with a custom secondary nav.
* Select a page to add a custom secondary nav. I chose the [Hero Height Refinements page](http://sparkbox-sandbox.suhumsci.loc/qa/hero-height-refinements)
* In the blue Drupal admin menu located beneath the site navigation, click on `Layout`
* Within `Section 2` of the layout builder, click `+ Add block
* A list of block to add will open to the right hand side, scroll down this list and select `Test Menu`. You will see `Test Menu` listed twice. Select one of them. If you do not see `HTML AND STYLE OPTIONS` displayed in the pop-up window, go back and select the other one.
add block
configure block
* Under `HTML AND STYLE OPTIONS` add `menu_block__main` in the Theme hook suggestion form field.
* Add block
* Save layout
* Go back to your page and confirm your new `Test menu` navigation looks like the secondary navigation
* Click on the contextual link for `Test menu` to `Edit menu`
* Add an external link to `Test menu`
* Confirm the external link in `Test menu` looks the same as the other links in the custom secondary nav
6. Add a nested external link into the secondary nav and confirm that the styles are the same as the other links

### CODE REVIEW

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr724-inhg2i7otoj0yalohbeih63zsknffdoq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5f627a8e6ea650d7e81844a6

Visual Diffs:
- https://dashboard.tugboat.qa/5f627a8e6ea650d7e81844a6/visualdiffs

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr724-inhg2i7otoj0yalohbeih63zsknffdoq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5f627a8e6ea650d7e81844a6

Visual Diffs:
- https://dashboard.tugboat.qa/5f627a8e6ea650d7e81844a6/visualdiffs

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr724-inhg2i7otoj0yalohbeih63zsknffdoq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5f627a8e6ea650d7e81844a6

Visual Diffs:
- https://dashboard.tugboat.qa/5f627a8e6ea650d7e81844a6/visualdiffs

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr724-inhg2i7otoj0yalohbeih63zsknffdoq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5f627a8e6ea650d7e81844a6

Visual Diffs:
- https://dashboard.tugboat.qa/5f627a8e6ea650d7e81844a6/visualdiffs

**Review by rkelbel — APPROVED** [review]
This looks and works great. 
Awesome job Heather!

Alt Text

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr724-inhg2i7otoj0yalohbeih63zsknffdoq.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5f627a8e6ea650d7e81844a6

Visual Diffs:
- https://dashboard.tugboat.qa/5f627a8e6ea650d7e81844a6/visualdiffs

**Pull request merged**
