### PR TITLE
HSD8-744 fix menu keyboard

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Fix keyboard navigation on main menu

# Need Review By (Date)
- asap

# Urgency
- high

# Steps to Test
1. checkout this branch
1. clear caches
1. navigate the main menu and ensure you can see where you are and you can click (enter) on items.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr446-wje4ntwnqfvmqpsd381bqzvatuqhfbkn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e20ff6d6ffa7b0c8ef8ee2c

Visual Diffs:
- https://dashboard.tugboat.qa/5e20ff6d6ffa7b0c8ef8ee2c/visualdiffs

**Review by sherakama — APPROVED** [review]
GTG

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr446-wje4ntwnqfvmqpsd381bqzvatuqhfbkn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e20ff6d6ffa7b0c8ef8ee2c

Visual Diffs:
- https://dashboard.tugboat.qa/5e20ff6d6ffa7b0c8ef8ee2c/visualdiffs

**Comment by pookmish** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr446-wje4ntwnqfvmqpsd381bqzvatuqhfbkn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/5e20ff6d6ffa7b0c8ef8ee2c

Visual Diffs:
- https://dashboard.tugboat.qa/5e20ff6d6ffa7b0c8ef8ee2c/visualdiffs

**Pull request merged**
