### PR TITLE
SHS-5869: Fix width in small screen sizes in Drupal user login form

### PR DESCRIPTION
**Pull request by mariannuar**
# READY FOR REVIEW

## Summary
Fix width in small screen sizes in Drupal user login form

## Need Review By (Date)
10/15

## Urgency
medium

## Steps to Test
1. Go to `/user/login`
2. Verify the width of the input looks good in all screen sizes

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1657-yywycpszwnmvfoqatm0qjnhx8abbs9zw.tugboatqa.com
- https://hs-colorful-yywycpszwnmvfoqatm0qjnhx8abbs9zw.tugboatqa.com
- https://hs-traditional-yywycpszwnmvfoqatm0qjnhx8abbs9zw.tugboatqa.com
- https://english-yywycpszwnmvfoqatm0qjnhx8abbs9zw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/670e92b1213f29084134bcbe

Visual Diffs:
- https://dashboard.tugboatqa.com/670e92b1213f29084134bcbe/visualdiffs

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1657-yywycpszwnmvfoqatm0qjnhx8abbs9zw.tugboatqa.com
- https://hs-colorful-yywycpszwnmvfoqatm0qjnhx8abbs9zw.tugboatqa.com
- https://hs-traditional-yywycpszwnmvfoqatm0qjnhx8abbs9zw.tugboatqa.com
- https://english-yywycpszwnmvfoqatm0qjnhx8abbs9zw.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/670e92b1213f29084134bcbe

Visual Diffs:
- https://dashboard.tugboatqa.com/670e92b1213f29084134bcbe/visualdiffs

**Comment by mariannuar** [comment]
@ahughes3 The fix for the small screen sizes is ready for review!

**Review by ahughes3 — APPROVED** [review]
looks good!

**Comment by ahughes3** [comment]
@joegl this is a fix that we would like to get in this week's release for a minor front end issue we saw on stage with work from https://github.com/SU-HSDO/suhumsci/pull/1651

**Review by joegl — APPROVED** [review]

**Pull request merged**
