### PR TITLE
SHS-5811: Add "logout" button to sites

### PR DESCRIPTION
**Pull request by codechefmarc**
# READY FOR REVIEW

## Summary
- Updates composer.json to point to a forked repo of the `stanford_samlauth` module that adds an optional logout button.

## Need Review By (Date)
2024-09-30

## Urgency
low

## Steps to Test
1. On a logged out page of the site, verify that the login button still exists in the footer.

Screenshot 2024-09-26 at 5 02 59 PM

2. Login to the site
3. Visit the "SAML SUNetID Block" block configuration page either by going to the "Block layout page" and clicking "Configure" next to the "SAML SUNetID Block" block or hovering over the block on the front-end and clicking "Configure" in the context menu.
4. Verify there are 2 new fields: "Enable logout button" and "SUNETID log-out link text"

Screenshot 2024-09-26 at 5 13 36 PM

5. Test enabling and disabling the logout button and verify on the front-end that the logout button appears and disappears.

Screenshot 2024-09-26 at 5 16 59 PM

6. Test changing the logout button text and verify on the front-end that the button text changes.
7. Test using the logout button and verify that it correctly logs the user out of the system. If you were on a specific page, after logout, the system will attempt to redirect to the page you were on.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1637-1l02k7kood5keyrrtdsm0heo6okzzs7s.tugboatqa.com
- https://hs-colorful-1l02k7kood5keyrrtdsm0heo6okzzs7s.tugboatqa.com
- https://hs-traditional-1l02k7kood5keyrrtdsm0heo6okzzs7s.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f5ef046f1e8632c5eaf2a8

Visual Diffs:
- https://dashboard.tugboatqa.com/66f5ef046f1e8632c5eaf2a8/visualdiffs

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1637-1l02k7kood5keyrrtdsm0heo6okzzs7s.tugboatqa.com
- https://hs-colorful-1l02k7kood5keyrrtdsm0heo6okzzs7s.tugboatqa.com
- https://hs-traditional-1l02k7kood5keyrrtdsm0heo6okzzs7s.tugboatqa.com
- https://english-1l02k7kood5keyrrtdsm0heo6okzzs7s.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/66f5ef046f1e8632c5eaf2a8

Visual Diffs:
- https://dashboard.tugboatqa.com/66f5ef046f1e8632c5eaf2a8/visualdiffs

**Comment by codechefmarc** [comment]
@cienvaras - I couldn't test an actual SUNet login locally or via Tugboat, but I don't think that's necessary - no code changes related to the SUNet login as this only adds a logout button. So, I just used `drush uli` and the Tugboat logins to test this.

**Comment by codechefmarc** [comment]
@cienvaras - hold off on review for a bit - Dave and I chatted about some additional things around this ticket and I need to make some changes first. I will let you know when it's ready for a review. Thanks!

**Pull request closed without merging**
