### PR TITLE
feat(STN-391): adds styles for padded card utility

### PR DESCRIPTION
**Pull request by silverli**
# READY FOR REVIEW

## Summary
Adds `hb-padded-cards` utility that can be added to views or the layout builder "components' area for pages with cards, including:

- vertical cards
- horizontal cards
- structured cards
- post cards (not vertical linked)
- date stacked horizontal card
- date stacked vertical card

## Steps to Test
1. Check `npm run test` passes.
2. On a page with postcards, use layout builder to add `hb-padded-cards` to the Layout builder Components area as a class.
3. On a page with a card view, add the `hb-padded-cards` class to the view under "Contextual Filters" like so:

Screen Shot 2020-05-21 at 4 01 23 PM
4. Make sure to check all instances of cards, including:

- [x] vertical cards
- [x]  horizontal cards
- [x] structured cards
- [x] post cards (not vertical linked)
- [x] date stacked horizontal card
- [x] date stacked vertical card

Browser Testing
- [x] Chrome
- [x] IE11
- [x] Firefox
- [x] Safari

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

### CODE REVIEW

**Review by bryanbraun — APPROVED** [review]
Honestly, This looks great. I'm excited about how quickly it came together!

I'm going to hold on merging for a few things:

- Running the class-name by H&S to see how they feel about it.
  - Also: documenting this class in [our pattern docs](https://docs.google.com/document/d/1Vgn0HCxmGgREBw8VieGfeMlS0kuT7pFUoJT6ThEwxcg/edit).
- Giving us a chance to demo this at a standup before merging.
- Capturing some screenshots in the ticket.

Otherwise I'm calling this good. 👍

***

*Update: Alex said their team would prefer to use`.hb-raised-cards` so I'll make that change, confirm it's good and get it merged.*

**Comment by silverli** [comment]
@bryanbraun here are screenshots, I'll put them in JIRA too:
Screen Shot 2020-05-21 at 3 19 10 PM
Screen Shot 2020-05-21 at 3 19 17 PM
Screen Shot 2020-05-21 at 3 22 00 PM
Screen Shot 2020-05-21 at 3 23 11 PM
Screen Shot 2020-05-21 at 3 24 01 PM
Screen Shot 2020-05-21 at 3 27 27 PM
Screen Shot 2020-05-21 at 3 28 17 PM
Screen Shot 2020-05-21 at 3 29 35 PM
Screen Shot 2020-05-21 at 4 01 23 PM

**Comment by bryanbraun** [comment]
I renamed the class on Alex's recommendation, but otherwise all is good!

**Comment by silverli** [comment]
hb-raised-cards



hb-stretch-vertical-linked-cards

**Pull request merged**
