### PR TITLE
Shs 77 megamenu unpublished styles

### PR DESCRIPTION
**Pull request by ryanhagerty**
## Summary
This adds styles to visually differentiate unpublished nodes in the the mega menu.

## Steps to Test
1. Enable the new megamenu, go to the main menu (`/admin/structure/menu/manage/main`) and unpublish a page. 
2. Verify that it gets the golden background to signify its unpublished like in the screenshots below.

## Screenshots
Screen Shot 2022-08-22 at 3 44 31 PM

Screen Shot 2022-08-22 at 3 44 25 PM

Screen Shot 2022-08-22 at 3 44 45 PM

## Notes
We'll add this after the current release to give enough time for testing.

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1164-plghkhyfgcc59mb18hyaixtw8qg3qpbm.tugboatqa.com
- https://hs-colorful-plghkhyfgcc59mb18hyaixtw8qg3qpbm.tugboatqa.com
- https://hs-traditional-plghkhyfgcc59mb18hyaixtw8qg3qpbm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6303dd6dfe628283134ad984

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1164-plghkhyfgcc59mb18hyaixtw8qg3qpbm.tugboatqa.com
- https://hs-colorful-plghkhyfgcc59mb18hyaixtw8qg3qpbm.tugboatqa.com
- https://hs-traditional-plghkhyfgcc59mb18hyaixtw8qg3qpbm.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6303dd6dfe628283134ad984

**Comment by Rain-kanyini** [comment]
Hey @ryanhagerty . I've reviewed this Pr and I believe that it passes, before I click the "review" button I just want to double check that I'm testing this is the correct space.

Your screen shots are of ` Stanford: Center For Website Studies : School of Humanities and Sciences`

The tickets screenshots are of ` Stanford: Department Of Classics : School of Humanities and Sciences`

I tested this ticket on: `Stanford: Department of Music: School of Humanities and Sciences`

image

I can verify that when a page is unpublished, it does have the styling that the ticket discribes!

The ticket mentions testing on the music-dev, so that's why I went to the music-url?  I hope I tested this in the correct place! If so, I believe that this is good! Upon your feedback (if I did test this in the right place) I'll hit the approve button :)

**Comment by ryanhagerty** [comment]
@Gregg-Hendrix Yeah, this is for 'all' the colorful sites, so I tested on HS Colorful, which is their standard kind of 'playground' site.

I'm still on Gitpod, so it's the only site I can test on. Lando still doesn't work for me.

**Review by Rain-kanyini — APPROVED** [review]

**Comment by Rain-kanyini** [comment]
> @Gregg-Hendrix Yeah, this is for 'all' the colorful sites, so I tested on HS Colorful, which is their standard kind of 'playground' site.
> 
> I'm still on Gitpod, so it's the only site I can test on. Lando still doesn't work for me.

@ryanhagerty thank you for letting me know how the HS Colorful applys to 'all' colorful sites :)! Its now been approved :)!

**Pull request merged**
