### PR TITLE
9.3.25

### PR DESCRIPTION
**Pull request by su-sws-jira**
9.3.25 Release

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Comment by callinmullaney** [comment]
@pookmish Can you recompile sass from `docroot/themes/humsci/humsci_basic` and commit those CSS file changes? It looks like the Traditional theme in the stage environments isn't reflecting the changes we made to the sass files. Thanks! 

(I attempted to do this but github notified me this is a locked branch)

**Comment by pookmish** [comment]
Please create a branch, compile the css, and create a PR. same as any other change.

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Comment by callinmullaney** [comment]
Sure thing @pookmish - Here is the PR with only the compiled files: https://github.com/SU-HSDO/suhumsci/pull/1166

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1153-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-colorful-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com
- https://hs-traditional-yq7ysikeh1jjhnhs0thjxdcihkcjx2uz.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62e9a8befe628283135b6941

**Pull request merged**
