### PR TITLE
SHS-5885: Remove "Admin Login Path" module

### PR DESCRIPTION
**Pull request by cienvaras**
# READY FOR REVIEW

## Summary
- Remove `admin_login_path` from project dependencies

## Need Review By (Date)
11/06

## Urgency
medium

## Steps to Test
1. Log in to the [Tugboat test site](https://pr1674-7f0capyn8pgsllm1hfmwc4ffftug5ovg.tugboatqa.com/user/login)
2. Visit the [modules admin page](https://pr1674-7f0capyn8pgsllm1hfmwc4ffftug5ovg.tugboatqa.com/admin/modules), search for "admin login path". Confirm that the module is not available anymore.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208664616401062

### CODE REVIEW

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1674-2szhiub8qzpirnhswa0aho2yvinjryrf.tugboatqa.com
- https://hs-colorful-2szhiub8qzpirnhswa0aho2yvinjryrf.tugboatqa.com
- https://hs-traditional-2szhiub8qzpirnhswa0aho2yvinjryrf.tugboatqa.com
- https://english-2szhiub8qzpirnhswa0aho2yvinjryrf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6722aee93e2dd2b98c48962b

Visual Diffs:
- https://dashboard.tugboatqa.com/6722aee93e2dd2b98c48962b/visualdiffs

**Comment by cienvaras** [comment]
@ahughes3 Ready for you to review.

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1674-2szhiub8qzpirnhswa0aho2yvinjryrf.tugboatqa.com
- https://hs-colorful-2szhiub8qzpirnhswa0aho2yvinjryrf.tugboatqa.com
- https://hs-traditional-2szhiub8qzpirnhswa0aho2yvinjryrf.tugboatqa.com
- https://english-2szhiub8qzpirnhswa0aho2yvinjryrf.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6722aee93e2dd2b98c48962b

Visual Diffs:
- https://dashboard.tugboatqa.com/6722aee93e2dd2b98c48962b/visualdiffs

**Comment by ahughes3** [comment]
@cienvaras The module appeared when I searched for Admin Login Path

Screenshot 2024-10-30 at 6 03 40 PM

**Comment by cienvaras** [comment]
@ahughes3 Sorry about that, I forgot that changing installed modules requires to build the tugboat test site without using a base preview. It's ready for testing again.

**Review by ahughes3 — APPROVED** [review]
LGTM!

**Review by joegl — APPROVED** [review]

**Pull request merged**
