### PR TITLE
Shs 54 percy local

### PR DESCRIPTION
**Pull request by ryanhagerty**
## Summary
This adds the necessary items for Percy testing and updates the `README` with instructions on how to use.

## Steps to Test
1. Get access to the Percy organization from Joey if you haven't already.
2. Go to Percy.io and under 'Project Settings' copy the entire line under 'Project Token' into a `.env` file in the `humsci_basic` directory (same directory as the `package.json` for this theme). So the file will be `PERCY_TOKEN=XXX`
3. See the NOTES below for an additional step.
4. Install percy with `npm install`
5. Run `npm run visreg` and ensure it outputs links to the builds for both the Traditional/Colorful themes. 

## Notes
In order to have consistent testing, we need to ensure certain features are enabled/disabled before testing. These include:
* The Colorful site should use the new V2 Megamenu
* The Traditional site should use the old V1 Megamenu
* Both Colorful and Traditional sites should have the 'Use Animation Enhancements' feature turned off on their respective theme settings.

## Screenshots
Screen Shot 2022-09-26 at 10 02 03 AM

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1185-ecxcyxennhw8emjk25wtuwqpyr37sars.tugboatqa.com
- https://hs-colorful-ecxcyxennhw8emjk25wtuwqpyr37sars.tugboatqa.com
- https://hs-traditional-ecxcyxennhw8emjk25wtuwqpyr37sars.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6331b22fd65209e3aa0ef279

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1185-ecxcyxennhw8emjk25wtuwqpyr37sars.tugboatqa.com
- https://hs-colorful-ecxcyxennhw8emjk25wtuwqpyr37sars.tugboatqa.com
- https://hs-traditional-ecxcyxennhw8emjk25wtuwqpyr37sars.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6331b22fd65209e3aa0ef279

**Review by callinmullaney — CHANGES_REQUESTED** [review]
@ryanhagerty Functionally I think this is looking great! My own tests seem to fire without issues once I updated the mega menu config for colorful. Some re-organization I would like you to consider to make future expansion on this integration easier:
1. Can we consolidate all percy tests to `tests/percy` inside `humsci_basic`? 
2. Can we move and rename `.env` to `tests/percy.env` or maybe just `tests/percy/.env` ? 

The lines above will be required for when we consolidate all tests into `/tests/` so they can live alongside codeception and phpunit. I'm working on moving these npm scripts into the root of the project here: https://github.com/SU-HSDO/suhumsci/pull/1172 - This is just and FYI.

**Comment by ryanhagerty** [comment]
@callinmullaney NP - updates made. I moved the files to `tests/percy` but the `.env` file needs to stay in the same location as `package.json` otherwise Percy can't find its token.

**Comment by ryanhagerty** [comment]
I would consider it a bonus as it enables us to keep all our tokens in one location FWIW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1185-ecxcyxennhw8emjk25wtuwqpyr37sars.tugboatqa.com
- https://hs-colorful-ecxcyxennhw8emjk25wtuwqpyr37sars.tugboatqa.com
- https://hs-traditional-ecxcyxennhw8emjk25wtuwqpyr37sars.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6331b22fd65209e3aa0ef279

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1185-ecxcyxennhw8emjk25wtuwqpyr37sars.tugboatqa.com
- https://hs-colorful-ecxcyxennhw8emjk25wtuwqpyr37sars.tugboatqa.com
- https://hs-traditional-ecxcyxennhw8emjk25wtuwqpyr37sars.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/6331b22fd65209e3aa0ef279

**Review by callinmullaney — APPROVED** [review]
@ryanhagerty Thanks for the work in this PR and the changes you made as a result of my feedback. I'm going to approve and merge into our weekly release. 

Once in the release I'm going to update the readme a bit more. I've been digging a little bit into how percy is setup for other themes/projects and the preferred method on how to handle the percy token is to add it to your bashrc or zshrc file in your computer's home folder. I tested this approach and percy tests ran without issues even though there was no `.env` file present. We are already doing this for `blt` stuff and it's also appropriate to store it in this file because the token is unique to your user account. I'll leave you `.env` method as a secondary option but wanted to communicate this preferred method for future reference.

**Pull request merged**
