### PR TITLE
Shs 119 megamenu color pairing

### PR DESCRIPTION
**Pull request by ryanhagerty**
## Summary
This adds color pairing to the new megamenu for child submenus.

## Steps to Test
1. On the Colorful site, make sure the 'Local Masthead Variant' is set to dark (http://hs-colorful.suhumsci.loc/admin/appearance/settings/humsci_colorful)
2. Ensure that the new mega menu is enabled (Site options: http://hs-colorful.suhumsci.loc/admin/config/site-options - you will need to flush the cache for this to take effect).
3. Visit any page and check out the menu at mobile size. With a dark masthead, the text color should be white for all menu item levels.
4. At desktop, level two items should appear as the color pairing color. You can see the color pairing color on the theme settings page, the same as the one linked above. Mine is set to 'Cardinal' as seen in the screenshot below.
5. Level three items should be black. 
6. Go back to the theme settings and change the 'Local Masthead Variant' to default. 
7. Visit your testing page again and view the menu at mobile. Level two items should be the color pairing color while level three retains black.
8. View the menu at desktop, it should follow the same pattern as step 6: level two color pairing color, level three black.
9. Repeat these steps for the traditional theme. You will likely have to enable the mega menu.

## Screenshots
Screen Shot 2022-10-18 at 1 35 59 PM

## Notes
I don't see a release branch for us yet, so I set it to Mike's release branch.

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1206-r65mmklsmhojncs2lobmvy6eqv5b02fk.tugboatqa.com
- https://hs-colorful-r65mmklsmhojncs2lobmvy6eqv5b02fk.tugboatqa.com
- https://hs-traditional-r65mmklsmhojncs2lobmvy6eqv5b02fk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/634ee704fa87ab0cb0e1ca0b

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1206-r65mmklsmhojncs2lobmvy6eqv5b02fk.tugboatqa.com
- https://hs-colorful-r65mmklsmhojncs2lobmvy6eqv5b02fk.tugboatqa.com
- https://hs-traditional-r65mmklsmhojncs2lobmvy6eqv5b02fk.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/634ee704fa87ab0cb0e1ca0b

**Review by callinmullaney — CHANGES_REQUESTED** [review]
@ryanhagerty This looks pretty good to me. Can you update the `tertiary-darken-20` values in `/humsci_basic/src/scss/settings/_variables.colorful-pairings.scss` for the Cliff, Canyon, and Lake themes so they use the defined hex in the ticket? Looks like they are still using the `darken(#007c8f, 20%)` method.

**Review by callinmullaney — APPROVED** [review]
@ryanhagerty nevermind! I saw that you are out today and wanted to get this merged into our weekly release. Update the pairing definitions and approving.

**Pull request merged**
