### PR TITLE
Fix: Missing Bourbon Library stylesheet error when compiling

### PR DESCRIPTION
**Pull request by callinmullaney**
# READY FOR REVIEW

## Summary
- After the percy integration there was a lost patch in `package-lock.json` that allowed the Decanter FE Library to locate and import Bourbon stylesheet. This PR restores this functionality

## Need Review By (Date)
asap

## Urgency
high

## Steps to Test
1. Checkout branch or pull into an existing branch
2. Go to the `humsci_basic` theme directory, delete the existing `node_modules` directory, and run `npm install`
3. Once finished, run `npm run build` and verify there are no sass compiling errors
4. Next run `npm run visreg` and verify Percy is still able to run it's testing

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1207-flnyvejukun8wywymnvuoo8aonmpoyel.tugboatqa.com
- https://hs-colorful-flnyvejukun8wywymnvuoo8aonmpoyel.tugboatqa.com
- https://hs-traditional-flnyvejukun8wywymnvuoo8aonmpoyel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/634f1604fa87ab0cb0e303dc

**Comment by ryanhagerty** [comment]
@callinmullaney 

I'm still getting the same error related to `bourbon`. 

Things I did:
* I merged in this branch, deleted `node_modules`, can confirm the merge in `git log` and the error persists. 
* I then took the raw form of `package-lock.json` with your commit included, deleted `node_modules`, tried installing again, and the error persists.

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1207-flnyvejukun8wywymnvuoo8aonmpoyel.tugboatqa.com
- https://hs-colorful-flnyvejukun8wywymnvuoo8aonmpoyel.tugboatqa.com
- https://hs-traditional-flnyvejukun8wywymnvuoo8aonmpoyel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/634f1604fa87ab0cb0e303dc

**Comment by callinmullaney** [comment]
@ryanhagerty It might help if I actually pushed the correct package-lock.json file :facepalm:  - Pull the latest here and give it another go.

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1207-flnyvejukun8wywymnvuoo8aonmpoyel.tugboatqa.com
- https://hs-colorful-flnyvejukun8wywymnvuoo8aonmpoyel.tugboatqa.com
- https://hs-traditional-flnyvejukun8wywymnvuoo8aonmpoyel.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/634f1604fa87ab0cb0e303dc

**Review by ryanhagerty — APPROVED** [review]
Works for me 🌮

**Pull request merged**
