### PR TITLE
Sparkbox Sprint 40

### PR DESCRIPTION
**Pull request by rkelbel**
# READY FOR REVIEW

## Summary
- STN-734: Soundcloud Embed #877 
- STN-730: Gradient Hero Slider Styles #866 
- Chore: Compatibility Docs #872
- STN-759: Update gradient hero link field to linkit #878
- Fix: Gradient hero right align bug #879
- Chore: Enable gradient hero slider config by default #880 
- Config overrides for Paragraph components:
  - Gradient Hero Slider - Disabled on older themes and older rows only. #882  (Pending approval)
  - Color Band - Disabled on older themes and ALL rows. #881 (Pending approval)

### TASK LIST:

- [x] Add compiled CSS & JS
- [x] Run BackstopJS visual regression tests
- [x] Ensure Code Climate passes against the `develop` branch. Link here: https://codeclimate.com/github/SU-HSDO/suhumsci/pull/873
- [x] Assign to Mike for review.

## Need Review By (Date)
asap

## Urgency
high

## Steps to Test
1. `npm run test` should pass in the root folder
2. If you are interested in the testing steps for associated PRs, please take a look at the individual PR's description and "Steps to Test" section.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Sparkbox PR Checklist](../docs/SparkboxPRChecklist.md)

### CODE REVIEW

**Review by pookmish — APPROVED** [review]

**Comment by pookmish** [comment]
This will have to wait until after the H&S team is complete with their default config updates. It's alot of work to merge in their updates on top of all these config updates.

**Comment by rkelbel** [comment]
> This will have to wait until after the H&S team is complete with their default config updates. It's alot of work to merge in their updates on top of all these config updates.

Ok. Did you need us to communicate anything to H&S or should it be all good once that work has completed?

**Comment by pookmish** [comment]
I've already communicated with H&S. Nothing necessary at this time.

**Comment by rkelbel** [comment]
Great, thanks Mike!

**Comment by pookmish** [comment]
There appears to be an issue with the test now after i updated the branch with the latest from the 9.0.4-release branch. either the update hook didn't do what was expected or the configs didn't save correctly. please review and revise

**Comment by rkelbel** [comment]
> There appears to be an issue with the test now after i updated the branch with the latest from the 9.0.4-release branch. either the update hook didn't do what was expected or the configs didn't save correctly. please review and revise

I believe the configuration changes are now reconciled. We should be good.

**Pull request merged**
