### PR TITLE
Shs 26 accordion utility class

### PR DESCRIPTION
**Pull request by ryanhagerty**
## Summary
This adds a new utility class for accordions so that the appearance can be modified. 

## Steps to Test
1. Go to the Accordions page (usually `/accordions`). Edit the Layout (tab at top of page). Go to the Main Region and click Configure (screenshot below). In the 'Field Formatter Class' text box, add `hb-accordion-secondary`. Save the layout.
2. Visit the Accordion page and note the appearance is now changed. 
3. The look should be changed according to the ticket:
- In the sitting state, the outline is the secondary color with the standard body text color for heading/icon. 
- Hover animates to fill the box solid with primary color background and white heading/icon.
- On click, it returns to heading/icon in text color, but outline is now primary. Primary outline wraps around the entire content block.
- On hover of heading/icon block in the expanded state, heading/icon switches to secondary color.
4. Verify the same for the Traditional theme
5. Verify the new utility class didn't alter anything else except the accordion on the page

## Notes
I don't see a release branch anywhere, so I'm leaving it on develop for now. This PR only has one commit. 

## Screenshots
Screen Shot 2022-09-13 at 8 44 30 AM

Screen Shot 2022-09-13 at 8 41 37 AM

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1178-kq5h3imeazvb0dm7b5sovrtprha5uoqt.tugboatqa.com
- https://hs-colorful-kq5h3imeazvb0dm7b5sovrtprha5uoqt.tugboatqa.com
- https://hs-traditional-kq5h3imeazvb0dm7b5sovrtprha5uoqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63207c2f3f0369b586bea969

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1178-kq5h3imeazvb0dm7b5sovrtprha5uoqt.tugboatqa.com
- https://hs-colorful-kq5h3imeazvb0dm7b5sovrtprha5uoqt.tugboatqa.com
- https://hs-traditional-kq5h3imeazvb0dm7b5sovrtprha5uoqt.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63207c2f3f0369b586bea969

**Review by callinmullaney — APPROVED** [review]
@ryanhagerty color palette changes appear to match requirements and I think the documentation added to the `utility-classes.md` should be sufficient. Approving for merging into our release branch.

**Comment by callinmullaney** [comment]
@ryanhagerty no worries about setting the correct branch on this PR. I'll attempt to create these release branches on Monday's for us but setting things to `develop` is fine.

**Pull request merged**
