### PR TITLE
SHS-134: Codeception Documentation

### PR DESCRIPTION
**Pull request by codechefmarc**
# READY FOR REVIEW

## Summary
- Adds a new README.md that details which Codeception tests are run during the CI process.
- Currently this is formatted from the file structure, but could be reformatted into a more concise list if that works better.

## Urgency
low

## Steps to Test
1. Review Codeception README.md for structure and clarity

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1237-ywyoen0ipkmcbupqqqqzaadppa7ynmpg.tugboatqa.com
- https://hs-colorful-ywyoen0ipkmcbupqqqqzaadppa7ynmpg.tugboatqa.com
- https://hs-traditional-ywyoen0ipkmcbupqqqqzaadppa7ynmpg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a21e160645501a1e8e07fc

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1237-ywyoen0ipkmcbupqqqqzaadppa7ynmpg.tugboatqa.com
- https://hs-colorful-ywyoen0ipkmcbupqqqqzaadppa7ynmpg.tugboatqa.com
- https://hs-traditional-ywyoen0ipkmcbupqqqqzaadppa7ynmpg.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/63a21e160645501a1e8e07fc

**Review by hectorlj — APPROVED** [review]
Documentation looks great! Very thorough

**Review by callinmullaney — CHANGES_REQUESTED** [review]
@marcb4k The contents of the documentation looks good to me and makes sense what's being testing from a plain-english standpoint. I think this will help non-devs understand exactly what codeception is testing without the need to look through code. That being said, I see why you add  this readme to the codeception directory but I THINK this might be better organized in the existing `docs/` directory. That way, all documentation for the project is more consolidated. https://github.com/SU-HSDO/suhumsci/tree/develop/docs 

Otherwise, before we merge this into our release I'd like you to bring this to our next standup and run this by Tori/Joey/Marion to see if this makes sense for them.

Nice work!

**Comment by codechefmarc** [comment]
@callinmullaney - Moved to docs folder. Thanks!

**Review by callinmullaney — APPROVED** [review]

**Review by pookmish — APPROVED** [review]

**Pull request merged**
