### PR TITLE
SHS-4875: regression - hb-main-body-image-detail no longer wraps text next to image - in Chrome only

### PR DESCRIPTION
**Pull request by callinmullaney**
# READY FOR REVIEW

## Summary
- Fix regression where floated images specifically added through layout build main region were no longer floated and wrapping text.

## Need Review By (Date)
asap

## Urgency
high

## Steps to Test
1. Verify the original reported issue is still fixed. Go to `/events/colloquium-series` and verify the floated image next to "Colloquium Series" is no longer collapsing the view below it.
2. Spin up the "Gender" site and go to https://gender.suhumsci.loc/people/adrian-daub - verify the image for Adrian Duab is floated right and the text below it is properly wrapping around the image. 
image (14)

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Review by ryanhagerty — CHANGES_REQUESTED** [review]
@callinmullaney I'm seeing the same behavior on a regular branch and this branch, LMK if this is the correct behavior. Are there any layout classes I need to add?

Screenshot 2023-03-21 at 8 48 01 AM

**Comment by callinmullaney** [comment]
@ryanhagerty chatted with Mike and there are some additional steps we need to add/document in our lando setup. The inconsistency that is happening here is due to Layout Builder config not importing due to `config_ignore` settings. So what you are seeing isn't accurate to production.
When I directly copied mark up (everything inside `.main-content` wrapper) and injected into my local I was seeing the correct layout. Screenshot from 2023-03-21 10-14-32

Also, the original issue where views were getting floated around the image is still in place. I opted for the solution to be specific to views so help avoid any other one-off situations this `clear` could affect.
Screenshot from 2023-03-21 10-49-20

**Comment by ryanhagerty** [comment]
@callinmullaney Thanks for getting that clarification from Mike. Getting accurate data for these individual site edge cases is super important. Copy/pasting the markup from prod reflects your image:

Screenshot 2023-03-21 at 12 48 18 PM

**Review by ryanhagerty — APPROVED** [review]
🌮

**Pull request merged**
