### PR TITLE
HSD8-774 HSD8-1330 Improved group blocks for better usability and configuration

### PR DESCRIPTION
**Pull request by pookmish**
- 9.3.23
- HSD8-774 HSD8-1330 Improved group blocks for better usability and configuration

# READY FOR REVIEW

## Summary
_[briefly summarize the changes here]_

## Need Review By (Date)
_['10/30', 'asap', etc.]_

## Urgency
_['low', 'medium', 'high', etc.]_

## Steps to Test
1. _[First testing step]_
2. ...

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

### CODE REVIEW

**Comment by pookmish** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1146-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com
- https://hs-colorful-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com
- https://hs-traditional-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62c768d39782ffff42845323

**Comment by pookmish** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1146-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com
- https://hs-colorful-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com
- https://hs-traditional-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62c768d39782ffff42845323

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1146-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com
- https://hs-colorful-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com
- https://hs-traditional-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62c768d39782ffff42845323

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1146-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com
- https://hs-colorful-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com
- https://hs-traditional-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62c768d39782ffff42845323

**Comment by su-sws-jira** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1146-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com
- https://hs-colorful-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com
- https://hs-traditional-7jmeflslap8xmq0vudh68ampz8koznd8.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/62c768d39782ffff42845323

**Pull request merged**
