### PR TITLE
SHS:5892: Site managers can perform actions on user accounts that don't make sense with SSO

### PR DESCRIPTION
**Pull request by cienvaras**
# READY FOR REVIEW

## Summary
- Remove "Cancel the selected user account(s)" and "Update URL Alias" bulk actions from the user list view
- In the user edit form, hide the URL alias related fields for all users and the "Cancel User" button for non admin users

## Need Review By (Date)
12/04

## Urgency
medium

## Steps to Test
1. Log into the [tugboat test site](https://hs-colorful-kea8cw1nuentjq5kebwi6lryjgqsr8au.tugboatqa.com/user/login)
2. Visit the [People view](https://hs-colorful-kea8cw1nuentjq5kebwi6lryjgqsr8au.tugboatqa.com/admin/users)
3. Select one or more users. Confirm one or more users and confirm that the following actions are not available anymore on the "Action" selector that appears at the bottom of the list:
    - Update URL alias
    - Cancel the selected user account(s)
4. For any user, click on the "Edit" button in the "Operations" column at the right. Confirm that:
    - There are no fields related to the URL alias visible
    - The "Cancel account" button is present at the bottom of the form
5. [Masquerade](https://hs-colorful-kea8cw1nuentjq5kebwi6lryjgqsr8au.tugboatqa.com/admin/users/masquerade) as an user with the "Site Manager" role (Lindsey)
6. Repeat steps 2 through 4. Everything should be the same as for the administrator user, **except that the "Cancel account" button in the user edit form shouldn't be present**.

## PR Checklist
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)
- [Humsci Basic PR Checklist](https://github.com/SU-HSDO/suhumsci/blob/develop/docs/HumsciBasicPRChecklist.md)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1208827336999823

### CODE REVIEW

**Comment by cienvaras** [comment]
@joegl Before passing this to @ahughes3 I wanted a quick check on our approach. The goal of the ticket is to remove some user actions that don't make sense in a site with SSO. We removed them from the bulk operations in the user list, but also want to remove them from the user edit form. The easiest way we found is to use a form alter and set the `#access` to `FALSE`, but I wanted to check if you see any potential issue or if you consider that a different approach is better. Thanks!

**Comment by joegl** [comment]
@cienvaras The approach seems fine but a little broad. I'd like to talk H&S about this one though, because there is at least one site where Drupal accounts are created without SSO and users need to be deleted regularly. I think adding a custom permission to control this would help, and then we could still allow Administrators (those with the Developer role) to delete users.

**Comment by cienvaras** [comment]
@joegl checked with @ahughes3 and confirmed the requirements:

> Only the developer role needs the ability to delete users, and no role needs to have the ability to update the URL alias of a user.

Based on this, we don't need a new permission, I just updated the form alter to check for the user roles when hiding the "Cancel account" button.

@ahughes3 This one will be ready for you to test as soon as Tugboat is working again.

**Comment by joegl** [comment]
@ahughes3 When we talked about this on Tuesday we said it should only remove the bulk cancel action and not the cancel button on the user edit form. This PR currently removes both. I just want to confirm that's what you want.

**Comment by ahughes3** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Links:
- https://pr1682-kea8cw1nuentjq5kebwi6lryjgqsr8au.tugboatqa.com
- https://hs-colorful-kea8cw1nuentjq5kebwi6lryjgqsr8au.tugboatqa.com
- https://hs-traditional-kea8cw1nuentjq5kebwi6lryjgqsr8au.tugboatqa.com
- https://english-kea8cw1nuentjq5kebwi6lryjgqsr8au.tugboatqa.com
- https://history-kea8cw1nuentjq5kebwi6lryjgqsr8au.tugboatqa.com
- https://west-kea8cw1nuentjq5kebwi6lryjgqsr8au.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/673f582e513b09d01c53abbf

**Comment by ahughes3** [comment]
@joegl In discussing with the web team, we have removed users manually on the Women's leadership site as a support request for the unit in the past and will continue that process. We want to restrict the ability to Cancel Accounts to just the Developer role as Site Managers do not need the ability to cancel any user accounts. In testing on Tugboat it looks like as a Developer I can still Cancel an Account from the User's edit page and as a Site Manager I no longer have that ability, which meets the requirements.

**Comment by joegl** [comment]
> @joegl In discussing with the web team, we have removed users manually on the Women's leadership site as a support request for the unit in the past and will continue that process. We want to restrict the ability to Cancel Accounts to just the Developer role as Site Managers do not need the ability to cancel any user accounts. In testing on Tugboat it looks like as a Developer I can still Cancel an Account from the User's edit page and as a Site Manager I no longer have that ability, which meets the requirements.

@ahughes3 Sounds good, thanks 👍 I'm ready to merge this one once you're done reviewing it 🚀

**Review by ahughes3 — APPROVED** [review]
looks good!

**Comment by ahughes3** [comment]
@pookmish this PR was approved by Joe and ready to merge but was waiting for my review approval - https://github.com/SU-HSDO/suhumsci/pull/1682#issuecomment-2494034658

**Review by pookmish — APPROVED** [review]
Simple enough. An alternative would've been to create a custom permission, but that's probably unnecessary here.

**Comment by pookmish** [comment]
Oh sorry @ahughes3 , i didn't notice your comment. Let me know if we need to revert or revise it.

**Comment by ahughes3** [comment]
@pookmish it was approved by me as well, we are good to go, thank you!

**Pull request merged**
